# Build database/schema/easycount_fresh_install.sql from easycount_schema.sql
# - Dual-tenant: groups, group_company_map, user_group_map, account_group_map, tenant_module_policy
# - scope_type / scope_id baked into scoped tables (no ALTER)
# - Extra tables: process, process_day, ownership history, company_auto_renew_request
# Usage: .\database\scripts\build_fresh_install_schema.ps1

$ErrorActionPreference = 'Stop'
$Root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent
$SchemaDir = Join-Path (Join-Path $Root 'database') 'schema'
$SourcePath = Join-Path $SchemaDir 'easycount_schema.sql'
$OutPath = Join-Path $SchemaDir 'easycount_fresh_install.sql'

if (-not (Test-Path $SourcePath)) {
    throw "Missing source schema: $SourcePath"
}

$sql = Get-Content -Path $SourcePath -Raw -Encoding UTF8
$sql = $sql -replace "`r`n", "`n" -replace "`r", "`n"

$header = @'
-- =============================================================================
-- EasyCount — fresh database install (full schema, dual-tenant group + company)
-- =============================================================================
-- Generated by: database/scripts/build_fresh_install_schema.ps1
-- Source base:  database/schema/easycount_schema.sql
--
-- Includes:
--   - All tables from easycount_schema (games + banks merge)
--   - groups / group_company_map / user_group_map / account_group_map / tenant_module_policy
--   - scope_type + scope_id on tenant-scoped tables (no ALTER migrations needed)
--   - process + process_day (required by Data Capture / Formula)
--   - company auto-renew columns + company_auto_renew_request
--   - company_ownership_history + group_ownership_history
--   - domain_list_fee_settings group_price / company_price / period_prices
--
-- Fresh install (example):
--   mysql -u root -e "DROP DATABASE IF EXISTS easycount; CREATE DATABASE easycount CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
--   mysql -u root easycount < database/schema/easycount_fresh_install.sql
--
-- Re-generate after editing easycount_schema.sql:
--   powershell -File database/scripts/build_fresh_install_schema.ps1
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';

CREATE DATABASE IF NOT EXISTS `easycount` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `easycount`;

'@

# Drop old header through first USE (keep body from first CREATE TABLE)
$sql = $sql -replace '(?s)^.*?USE `easycount`;\s*', ''

$scopeAfterCompanyId = @'
  `scope_type` enum('company','group') NOT NULL DEFAULT 'company' COMMENT 'Tenant scope: company or group ledger',
  `scope_id` bigint UNSIGNED DEFAULT NULL COMMENT 'Numeric scope: company.id or groups.id',
'@

function Inject-ScopeAfterCompanyId {
    param([string]$Block, [string]$CompanyIdLinePattern)
    if ($Block -notmatch [regex]::Escape($CompanyIdLinePattern)) { return $Block }
    return $Block.Replace($CompanyIdLinePattern, ($CompanyIdLinePattern + "`r`n" + $scopeAfterCompanyId.TrimEnd()))
}

$scopeInjectPattern = '(?ms)(CREATE TABLE `(?:account_company|currency|data_captures|data_capture_details|data_capture_templates|description|transactions|transactions_deleted|transaction_entry|user_company_map)` \((?:(?!`scope_type`).)+?)(  `company_id`[^\n]+)(\n)'
$scopeTail = ($scopeAfterCompanyId.TrimEnd() -replace ',\s*$', '')
$sql = [regex]::Replace($sql, $scopeInjectPattern, {
    param($m)
    $companyLine = $m.Groups[3].Value.TrimEnd()
    if ($companyLine -notmatch ',$') { $companyLine += ',' }
    $m.Groups[1].Value + $m.Groups[2].Value + $companyLine + "`n" + $scopeTail + "`n"
})
# Fix stray comma-only lines from scope injection
$sql = $sql -replace ",\r?\n,\r?\n", ",`n"
$sql = $sql -replace "(`scope_id`[^\r\n]+),\r?\n(\) ENGINE)", "`$1`n`$2"

# company: auto-renew + note on group_id (regex — line endings normalized to LF)
$sql = [regex]::Replace($sql, '(?ms)(CREATE TABLE `company` \(.+?`group_id` varchar\(50\) DEFAULT NULL)\s*(\) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;)', {
    param($m)
    $m.Groups[1].Value + " COMMENT 'Parent group code for subsidiary companies only (not group definition)',`n" +
    "  ``auto_renew_enabled`` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Subscription auto-renew enabled',`n" +
    "  ``auto_renew_period`` varchar(20) DEFAULT NULL COMMENT '7days|1month|3months|6months|1year',`n" +
    "  ``payment_customer_id`` varchar(255) DEFAULT NULL,`n" +
    "  ``payment_subscription_id`` varchar(255) DEFAULT NULL,`n" +
    "  ``auto_renew_updated_at`` datetime DEFAULT NULL,`n" +
    "  ``auto_renew_updated_by`` varchar(50) DEFAULT NULL`n" +
    $m.Groups[2].Value
})

# domain_list_fee_settings
$sql = [regex]::Replace($sql, '(?ms)CREATE TABLE `domain_list_fee_settings` \([\s\S]*?\) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;', @'
CREATE TABLE `domain_list_fee_settings` (
  `id` tinyint(3) UNSIGNED NOT NULL,
  `price` decimal(25,8) DEFAULT NULL COMMENT 'Legacy single price (synced from company 6-month)',
  `group_price` decimal(25,8) DEFAULT NULL COMMENT 'Default fee for group tenants',
  `company_price` decimal(25,8) DEFAULT NULL COMMENT 'Default fee for company tenants',
  `period_prices` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Per-period prices JSON' CHECK (json_valid(`period_prices`) OR `period_prices` IS NULL),
  `maintenance_fee` decimal(14,4) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
'@)

$dualTenantBlock = @'

-- -----------------------------------------------------------------------------
-- Dual-tenant: Group definition (separate from company rows)
-- -----------------------------------------------------------------------------

CREATE TABLE `groups` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_code` varchar(50) NOT NULL COMMENT 'Business group code e.g. AP, IG',
  `group_name` varchar(100) DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `owner_id` int UNSIGNED DEFAULT NULL COMMENT 'FK owner.id (domain owner)',
  `expiration_date` date DEFAULT NULL COMMENT 'Group subscription expiry',
  `permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Group permissions JSON' CHECK (json_valid(`permissions`) OR `permissions` IS NULL),
  `fee_share_allocations` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'Fee share JSON' CHECK (json_valid(`fee_share_allocations`) OR `fee_share_allocations` IS NULL),
  `created_by` varchar(50) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_groups_group_code` (`group_code`),
  KEY `idx_groups_owner_id` (`owner_id`),
  KEY `idx_groups_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Group tenants (login scope group)';

CREATE TABLE `group_company_map` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_id` bigint UNSIGNED NOT NULL COMMENT 'FK groups.id',
  `company_id` int UNSIGNED NOT NULL COMMENT 'FK company.id (subsidiary)',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_group_company` (`group_id`,`company_id`),
  KEY `idx_gcm_company_id` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Group to subsidiary company mapping';

CREATE TABLE `user_group_map` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL COMMENT 'FK user.id',
  `group_id` bigint UNSIGNED NOT NULL COMMENT 'FK groups.id',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_group` (`user_id`,`group_id`),
  KEY `idx_ugm_group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User access for group login';

CREATE TABLE `account_group_map` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `account_id` int NOT NULL COMMENT 'FK account.id (member)',
  `group_id` bigint UNSIGNED NOT NULL COMMENT 'FK groups.id',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_account_group` (`account_id`,`group_id`),
  KEY `idx_agm_group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Member account access for group login';

CREATE TABLE `tenant_module_policy` (
  `id` bigint UNSIGNED NOT NULL AUTO_INCREMENT,
  `scope_type` enum('company','group') NOT NULL,
  `scope_id` bigint UNSIGNED NOT NULL COMMENT 'company.id or groups.id',
  `module_key` varchar(50) NOT NULL COMMENT 'e.g. process, bankprocess',
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_module` (`scope_type`,`scope_id`,`module_key`),
  KEY `idx_tenant_module_scope` (`scope_type`,`scope_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Per-tenant module enablement';

'@

$insertMarker = '-- Table structure for table `group_ownership`'
if ($sql -notmatch [regex]::Escape($insertMarker)) { throw 'Insert marker not found: group_ownership' }
$sql = $sql.Replace($insertMarker, ($dualTenantBlock + $insertMarker))

$processBlock = @'

-- -----------------------------------------------------------------------------
-- Process (Formula / Data Capture) — not in games+banks merge export
-- -----------------------------------------------------------------------------

CREATE TABLE `process` (
  `id` int NOT NULL AUTO_INCREMENT,
  `process_id` varchar(50) NOT NULL,
  `description_id` int NOT NULL,
  `currency_id` int NOT NULL,
  `remove_word` text DEFAULT NULL COMMENT 'Comma-separated words to remove',
  `replace_word_from` varchar(255) DEFAULT NULL,
  `replace_word_to` varchar(255) DEFAULT NULL,
  `remark` text DEFAULT NULL,
  `status` enum('active','inactive') NOT NULL DEFAULT 'active',
  `dts_modified` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `modified_by` int DEFAULT NULL,
  `modified_by_type` enum('user','owner') DEFAULT 'user',
  `modified_by_owner_id` int UNSIGNED DEFAULT NULL,
  `dts_created` datetime NOT NULL DEFAULT current_timestamp(),
  `created_by` int DEFAULT NULL,
  `created_by_type` enum('user','owner') NOT NULL DEFAULT 'user',
  `created_by_owner_id` int DEFAULT NULL,
  `company_id` int UNSIGNED NOT NULL COMMENT 'FK company.id',
  `sync_source_process_id` int DEFAULT NULL COMMENT 'Multi-use formula sync source',
  PRIMARY KEY (`id`),
  KEY `idx_process_company` (`company_id`),
  KEY `idx_process_code` (`process_id`,`company_id`),
  KEY `idx_process_description` (`description_id`,`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Process records';

CREATE TABLE `process_day` (
  `id` int NOT NULL AUTO_INCREMENT,
  `process_id` int NOT NULL COMMENT 'FK process.id',
  `day_id` int NOT NULL COMMENT 'FK day.id',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_process_day` (`process_id`,`day_id`),
  KEY `idx_process_day_day` (`day_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Process-day association';

'@

$dayMarker = '-- Table structure for table `deleted_logs`'
$sql = $sql.Replace($dayMarker, ($processBlock + $dayMarker))

$extraTables = @'

CREATE TABLE `company_auto_renew_request` (
  `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` int UNSIGNED NOT NULL COMMENT 'FK company.id',
  `expiration_snapshot` date NOT NULL,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `period` varchar(20) DEFAULT NULL,
  `price` decimal(25,8) DEFAULT NULL,
  `from_account_id` int DEFAULT NULL,
  `to_account_id` int DEFAULT NULL,
  `transaction_id` int DEFAULT NULL,
  `new_expiration_date` date DEFAULT NULL,
  `processed_by` varchar(50) DEFAULT NULL,
  `processed_at` datetime DEFAULT NULL,
  `reject_reason` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_auto_renew_company_exp` (`company_id`,`expiration_snapshot`),
  KEY `idx_auto_renew_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `company_ownership_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `company_id` int NOT NULL,
  `effective_month` date NOT NULL COMMENT 'First day of month YYYY-MM-01',
  `account_id` int NOT NULL,
  `owner_type` enum('account','owner','user','group') NOT NULL DEFAULT 'account',
  `percentage` decimal(6,2) NOT NULL DEFAULT 0.00,
  `partner_group_id` varchar(50) DEFAULT NULL,
  `read_only` tinyint(1) NOT NULL DEFAULT 1,
  `saved_by` int DEFAULT NULL,
  `saved_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_co_hist_month_account` (`company_id`,`effective_month`,`account_id`,`owner_type`),
  KEY `idx_co_hist_company_month` (`company_id`,`effective_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `group_ownership_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `group_id` varchar(50) NOT NULL COMMENT 'Group code (matches groups.group_code)',
  `owner_id` int NOT NULL DEFAULT 0,
  `effective_month` date NOT NULL,
  `account_id` int NOT NULL,
  `owner_type` enum('owner','user','group') NOT NULL DEFAULT 'owner',
  `percentage` decimal(6,2) NOT NULL DEFAULT 0.00,
  `partner_group_id` varchar(50) DEFAULT NULL,
  `read_only` tinyint(1) NOT NULL DEFAULT 1,
  `saved_by` int DEFAULT NULL,
  `saved_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_go_hist_month_account` (`group_id`,`effective_month`,`account_id`,`owner_type`),
  KEY `idx_go_hist_group_month` (`group_id`,`effective_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

'@

$sql = $sql.Replace($insertMarker, ($extraTables + $insertMarker))

# Clean AUTO_INCREMENT seed numbers from dump (fresh DB starts at 1)
$sql = $sql -replace ', AUTO_INCREMENT=\d+', ''

# Fix account_company / currency CREATE to use AUTO_INCREMENT on id where needed - source uses MODIFY later

$dualTenantIndexes = @'

-- -----------------------------------------------------------------------------
-- Dual-tenant: indexes (scoped tables)
-- -----------------------------------------------------------------------------

ALTER TABLE `account_company`
  ADD KEY `idx_ac_scope` (`scope_type`,`scope_id`,`account_id`);

ALTER TABLE `currency`
  ADD KEY `idx_currency_scope_code` (`scope_type`,`scope_id`,`code`);

ALTER TABLE `data_captures`
  ADD KEY `idx_dc_scope_date` (`scope_type`,`scope_id`,`capture_date`);

ALTER TABLE `data_capture_details`
  ADD KEY `idx_dcd_scope` (`scope_type`,`scope_id`,`account_id`,`currency_id`);

ALTER TABLE `data_capture_templates`
  ADD KEY `idx_dct_scope` (`scope_type`,`scope_id`,`process_id`);

ALTER TABLE `description`
  ADD KEY `idx_description_scope` (`scope_type`,`scope_id`,`name`);

ALTER TABLE `transactions`
  ADD KEY `idx_transactions_scope_date` (`scope_type`,`scope_id`,`transaction_date`),
  ADD KEY `idx_transactions_scope_account` (`scope_type`,`scope_id`,`account_id`);

ALTER TABLE `transactions_deleted`
  ADD KEY `idx_deleted_tx_scope_date` (`scope_type`,`scope_id`,`transaction_date`);

ALTER TABLE `transaction_entry`
  ADD KEY `idx_te_scope` (`scope_type`,`scope_id`,`account_id`,`currency_id`);

ALTER TABLE `user_company_map`
  ADD KEY `idx_ucm_scope` (`user_id`,`scope_type`,`scope_id`);

-- -----------------------------------------------------------------------------
-- Dual-tenant: foreign keys
-- -----------------------------------------------------------------------------

ALTER TABLE `groups`
  ADD CONSTRAINT `fk_groups_owner` FOREIGN KEY (`owner_id`) REFERENCES `owner` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `group_company_map`
  ADD CONSTRAINT `fk_gcm_group_id` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_gcm_company_id` FOREIGN KEY (`company_id`) REFERENCES `company` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `user_group_map`
  ADD CONSTRAINT `fk_ugm_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_ugm_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `account_group_map`
  ADD CONSTRAINT `fk_agm_account` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_agm_group` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `company_auto_renew_request`
  ADD CONSTRAINT `fk_car_company` FOREIGN KEY (`company_id`) REFERENCES `company` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `process`
  ADD CONSTRAINT `fk_process_company` FOREIGN KEY (`company_id`) REFERENCES `company` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_process_description` FOREIGN KEY (`description_id`) REFERENCES `description` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_process_currency` FOREIGN KEY (`currency_id`) REFERENCES `currency` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `process_day`
  ADD CONSTRAINT `fk_process_day_process` FOREIGN KEY (`process_id`) REFERENCES `process` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_process_day_day` FOREIGN KEY (`day_id`) REFERENCES `day` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS = 1;

'@

# Insert before final SET FOREIGN_KEY_CHECKS = 1 if present, else append
if ($sql -match 'SET FOREIGN_KEY_CHECKS = 1;') {
    $sql = $sql -replace 'SET FOREIGN_KEY_CHECKS = 1;\s*$', $dualTenantIndexes
} else {
    $sql += "`r`n" + $dualTenantIndexes
}

$out = $header + $sql
[System.IO.File]::WriteAllText($OutPath, $out, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $OutPath ($((Get-Item $OutPath).Length) bytes)"
