# Merge schema/games_schema.sql + schema/banks_schema.sql into schema/easycount_schema.sql
# Shared tables come from games only; banks-only tables are appended from banks_schema.
# Usage: .\merge_easycount_schema.ps1

$ErrorActionPreference = 'Stop'
$SchemaDir = Join-Path (Split-Path $PSScriptRoot -Parent) 'schema'
$gamesPath = Join-Path $SchemaDir 'games_schema.sql'
$banksPath = Join-Path $SchemaDir 'banks_schema.sql'
$outPath = Join-Path $SchemaDir 'easycount_schema.sql'

$banksOnlyTableNames = @(
    'bank_process',
    'bank_process_accounting_resend_daily_guard',
    'bank_process_accounting_resend_daily_guard_backup',
    'bank_process_backup',
    'bank_process_maintenance_resend_pending',
    'bank_process_maintenance_resend_pending_backup',
    'process_accounting_posted',
    'submitted_processes',
    'submitted_processes_backup',
    'transactions',
    'transactions_backup',
    'transactions_deleted',
    'transactions_rate',
    'transactions_rate_backup',
    'transactions_rate_details',
    'transactions_rate_details_backup',
    'transaction_entry',
    'transaction_entry_backup'
)

function Get-SectionBlocks {
    param([string]$Sql, [string]$SectionKind)
    $blocks = @{}
    $bt = [char]0x60
    $gap = '\r?\n--\r?\n(?:\r?\n)?'
    switch ($SectionKind) {
        'create' {
            $pattern = "(?ms)^-- Table structure for table ${bt}([^${bt}]+)${bt}${gap}(CREATE TABLE ${bt}[^${bt}]+${bt}.*?;\r?\n)"
        }
        'index' {
            $pattern = "(?ms)^-- Indexes for table ${bt}([^${bt}]+)${bt}${gap}(ALTER TABLE ${bt}[^${bt}]+${bt}.*?;\r?\n)"
        }
        'autoinc' {
            $pattern = "(?ms)^-- AUTO_INCREMENT for table ${bt}([^${bt}]+)${bt}${gap}(ALTER TABLE ${bt}[^${bt}]+${bt}.*?;\r?\n)"
        }
        'constraint' {
            $pattern = "(?ms)^-- Constraints for table ${bt}([^${bt}]+)${bt}${gap}(ALTER TABLE ${bt}[^${bt}]+${bt}.*?;\r?\n(?:\r?\n)*?)"
        }
    }
    foreach ($m in [regex]::Matches($Sql, $pattern)) {
        $blocks[$m.Groups[1].Value] = $m.Groups[2].Value
    }
    return $blocks
}

function Join-TableSections {
    param([hashtable]$Blocks, [string[]]$Names, [string]$Label)
    $bt = [char]0x60
    ($Names | ForEach-Object {
        $n = $_
        if (-not $Blocks.ContainsKey($n)) { throw "Missing $Label section for ${bt}${n}${bt}" }
        "--`r`n-- $Label for table ${bt}${n}${bt}`r`n--`r`n`r`n" + $Blocks[$n]
    }) -join ''
}

$games = [IO.File]::ReadAllText($gamesPath)
$banks = [IO.File]::ReadAllText($banksPath)

$banksCreates = Get-SectionBlocks $banks 'create'
$banksIndexes = Get-SectionBlocks $banks 'index'
$banksAutoinc = Get-SectionBlocks $banks 'autoinc'
$banksConstraints = Get-SectionBlocks $banks 'constraint'

$banksCreateSql = Join-TableSections $banksCreates $banksOnlyTableNames 'Table structure'
$banksIndexSql = Join-TableSections $banksIndexes $banksOnlyTableNames 'Indexes'
$banksAutoincSql = Join-TableSections $banksAutoinc $banksOnlyTableNames 'AUTO_INCREMENT'
$banksConstraintNames = $banksOnlyTableNames | Where-Object { $banksConstraints.ContainsKey($_) }
$banksConstraintSql = if ($banksConstraintNames.Count -gt 0) {
    Join-TableSections $banksConstraints $banksConstraintNames 'Constraints'
} else { '' }

$markerIndexes = "`r`n--`r`n-- Indexes for dumped tables`r`n--`r`n"
$markerAutoinc = "`r`n--`r`n-- AUTO_INCREMENT for dumped tables`r`n--`r`n"
$markerConstraints = "`r`n-- --------------------------------------------------------`r`n`r`n--`r`n-- Constraints for dumped tables`r`n--`r`n"

$body = $games
$body = $body -replace '(?m)^SET NAMES utf8mb4;\r?\nSET FOREIGN_KEY_CHECKS = 0;\r?\n\r?\n', ''
$body = $body -replace '(?m)^SET FOREIGN_KEY_CHECKS = 1;\s*$', ''

$header = @"
-- Combined Games + Banks schema (merged from games_schema.sql + banks_schema.sql).
-- Generated by database/scripts/merge_easycount_schema.ps1 - re-run after editing source files.
-- Import: mysql -u root < database/schema/easycount_schema.sql
--   or:   mysql -u root easycount < database/schema/easycount_schema.sql

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE DATABASE IF NOT EXISTS ``easycount`` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ``easycount``;

"@

$merged = $header + $body
$merged = $merged.Replace($markerIndexes, "`r`n" + $banksCreateSql + $markerIndexes)
$merged = $merged.Replace($markerAutoinc, "`r`n" + $banksIndexSql + $markerAutoinc)
$merged = $merged.Replace($markerConstraints, "`r`n" + $banksAutoincSql + $markerConstraints)
$merged = $merged.Replace('SET FOREIGN_KEY_CHECKS = 1;', $banksConstraintSql + "`r`nSET FOREIGN_KEY_CHECKS = 1;")
$merged = $merged.Replace('utf8mb4_uca1400_ai_ci', 'utf8mb4_unicode_ci')

[IO.File]::WriteAllText($outPath, $merged, [Text.UTF8Encoding]::new($false))
$kb = [IO.File]::ReadAllBytes($outPath).Length / 1KB
Write-Host "Wrote $outPath ($([math]::Round($kb, 1)) KB)"
