import { interpolate } from "../shared/i18nHelpers.js";

export const AUTO_RENEW_I18N = {
  en: {
    pageTitle: "Auto Renew",
    pageSubtitle: "Review and approve subscription renewals for companies and groups expiring within 30 days.",
    company: "Company",
    companyTab: "Company",
    groupTab: "Group",
    tabPendingBadgeCompany: "{count} pending company renewals",
    tabPendingBadgeGroup: "{count} pending group renewals",
    expirationDate: "Expiration Date",
    timeRemaining: "Time Remaining",
    notSet: "Not set",
    noExpirationDate: "No expiration date",
    renewalPeriod: "Renewal Period",
    selectPeriod: "Select period…",
    period7days: "7 days",
    period1month: "1 month",
    period3months: "3 months",
    period6months: "6 months",
    period1year: "1 year",
    loadFailed: "Failed to load: {message}",
    readOnlyNotice: "Only C168 Owner or Admin can approve or reject renewals.",
    accessDenied: "You do not have access to Auto Renew.",
    noResults: "No renewal requests match your search or filters.",
    emptyTitle: "All clear for now",
    emptyHintPending: "No companies are within the 30-day renewal window, or all requests have been processed.",
    emptyHintApproved: "No approved renewals in recent history.",
    emptyHintRejected: "No rejected renewals in recent history.",
    emptyHintAll: "Nothing in the renewal queue right now. Check back when a company nears expiration.",
    searchPlaceholder: "Search company or name…",
    filterGroupLabel: "Filters",
    filterPending: "Pending",
    filterApproved: "Approved",
    filterRejected: "Rejected",
    filterShowAll: "Show All",
    colNo: "No.",
    colCompany: "Company",
    colGroup: "Group",
    colName: "Name",
    colPrice: "Price",
    colExpiration: "Expiration",
    colRemaining: "Remaining",
    colPeriod: "Period",
    colStatus: "Status",
    colFromAccount: "From Account",
    colToAccount: "To Account",
    colSubmitter: "Submitter",
    selectFromAccount: "From",
    selectToAccount: "To",
    comm: "Comm",
    commTooltip: "Open Company / Group Settings to configure share sync",
    commSettingsNotFound: "Could not load settings for this tenant",
    commSettingsLoadFailed: "Failed to open settings: {message}",
    approve: "Approve",
    reject: "Reject",
    delete: "Delete",
    cancel: "Cancel",
    confirmDeleteTitle: "Confirm Delete",
    confirmRejectTitle: "Confirm Reject",
    confirmApproveTitle: "Confirm Approve",
    processing: "Processing…",
    confirmApprove: "Approve renewal for {company}? This will extend expiration and create a payment.",
    confirmReject: "Clear Period and Account selections for {company}? Status stays pending.",
    confirmDelete: "Delete approved renewal for {company}? Payment will be removed and expiration reverted.",
    approvedSuccess: "Renewal approved",
    rejectedSuccess: "Selection cleared",
    deletedSuccess: "Renewal deleted — payment removed and request returned to pending",
    approveFailed: "Approve failed: {message}",
    rejectFailed: "Clear failed: {message}",
    deleteFailed: "Delete failed: {message}",
    noPriceHint: "Set Domain renewal price first",
    accountsNotResolved: "Customer account not linked in C168",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    statusDeleted: "Deleted",
    expExpired: "Expired",
    expToday: "Expires today",
    expDaysLeft: "{days} days left",
    prevPage: "Previous",
    nextPage: "Next",
    paginationOf: "{page} of {total}",
    pageInfo: "Page {page} / {total} · {count} requests",
    renewBadgePending: "Renew",
    renewBadgeApproved: "Renewed",
  },
  zh: {
    pageTitle: "自动续费审批",
    pageSubtitle: "审批 30 天内到期的客户公司与分组续费申请。",
    company: "公司",
    companyTab: "公司",
    groupTab: "集团",
    tabPendingBadgeCompany: "{count} 条待审批公司续费",
    tabPendingBadgeGroup: "{count} 条待审批集团续费",
    expirationDate: "到期日",
    timeRemaining: "剩余时间",
    notSet: "未设置",
    noExpirationDate: "尚未设置到期日",
    renewalPeriod: "续费周期",
    selectPeriod: "请选择周期…",
    period7days: "7 天",
    period1month: "1 个月",
    period3months: "3 个月",
    period6months: "6 个月",
    period1year: "1 年",
    loadFailed: "加载失败：{message}",
    readOnlyNotice: "仅 C168 Owner 或 Admin 可审批续费。",
    accessDenied: "您无权访问自动续费。",
    noResults: "没有符合搜索或筛选条件的续费请求。",
    emptyTitle: "目前没有待处理项",
    emptyHintPending: "暂无进入 30 天续费窗口的公司，或相关请求已全部处理。",
    emptyHintApproved: "近期没有已批准的续费记录。",
    emptyHintRejected: "近期没有已拒绝的续费记录。",
    emptyHintAll: "续费队列为空。公司临近到期时会自动出现在此。",
    searchPlaceholder: "搜索公司、名称或集团…",
    filterGroupLabel: "筛选",
    filterPending: "待审批",
    filterApproved: "已批准",
    filterRejected: "已拒绝",
    filterShowAll: "全部",
    colNo: "序号",
    colCompany: "公司",
    colGroup: "集团",
    colName: "名称",
    colPrice: "续费金额",
    colExpiration: "到期日",
    colRemaining: "剩余时间",
    colPeriod: "续费周期",
    colStatus: "状态",
    colFromAccount: "付款账户",
    colToAccount: "收款账户",
    colSubmitter: "提交人",
    selectFromAccount: "选择付款方",
    selectToAccount: "选择收款方",
    comm: "同步",
    commTooltip: "打开公司/集团设置，配置 Share 同步",
    commSettingsNotFound: "无法加载该租户的设置",
    commSettingsLoadFailed: "打开设置失败：{message}",
    approve: "批准",
    reject: "拒绝",
    delete: "删除",
    cancel: "取消",
    confirmDeleteTitle: "确认删除",
    confirmRejectTitle: "确认拒绝",
    confirmApproveTitle: "确认批准",
    processing: "处理中…",
    confirmApprove: "确认批准 {company} 的续费？将延长到期日并创建付款。",
    confirmReject: "清空 {company} 的周期与账户选择？状态保持待审批。",
    confirmDelete: "删除 {company} 的已批准续费？将删除付款并回退到期日。",
    approvedSuccess: "续费已批准",
    rejectedSuccess: "已清空选择",
    deletedSuccess: "已删除续费 — 付款已移除，请求回到待审批",
    approveFailed: "批准失败：{message}",
    rejectFailed: "清空失败：{message}",
    deleteFailed: "删除失败：{message}",
    noPriceHint: "请先在 Domain 设置续费价格",
    accountsNotResolved: "未找到客户在 C168 的关联账户",
    statusPending: "待审批",
    statusApproved: "已批准",
    statusRejected: "已拒绝",
    statusDeleted: "已删除",
    expExpired: "已过期",
    expToday: "今日到期",
    expDaysLeft: "剩余 {days} 天",
    prevPage: "上一页",
    nextPage: "下一页",
    paginationOf: "{page} / {total}",
    pageInfo: "第 {page} / {total} 页 · 共 {count} 条",
    renewBadgePending: "续费",
    renewBadgeApproved: "已续",
  },
};

export function getAutoRenewText(lang, key, params = {}) {
  const locale = lang === "zh" ? "zh" : "en";
  const raw = AUTO_RENEW_I18N[locale]?.[key] ?? AUTO_RENEW_I18N.en[key] ?? key;
  return interpolate(raw, params);
}
