import { interpolate, toLocale } from "../shared/i18nHelpers.js";

export const BANK_PROCESS_I18N = {
  en: {
    bankProcessList: "Bank Process List",
    accountingDue: "Accounting Due",
    addProcess: "Add Process",
    addAccount: "Add Account",
    selectDateRange: "Select date range",
    pickDate: "DD/MM/YYYY",
    selectEndDate: "Select end date",
    clearDate: "Clear",
    clearDateRange: "Clear date range",
    periodShortcutsAria: "Period shortcuts",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",
    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    search: "Search",
    filter: "Filter",
    filterDoubleClickClear: "Double-click to clear filters",
    filterClearAll: "Clear all filters",
    showAll: "Show All",
    showInactive: "Show Inactive",
    showOfficial: "Show Official",
    showEInvoice: "Show E-Invoice",
    showBlock: "Show Blocked",
    delete: "Delete",
    groupId: "Group:",
    groupFilterAll: "ALL",
    currency: "Currency:",
    currencyDragHint: "Drag to reorder · Click to filter",
    company: "Company:",
    pageOf: "{current} of {total}",
    readOnlyActionBlocked: "Read-only account: this action is not allowed.",
    failedLoadBankProcesses: "Failed to load bank processes",
    switchCompanyFailed: "Switch company failed",
    addCountryFailed: "Add country failed",
    countryAlreadyExists: "Country \"{country}\" already exists",
    countryCodeLettersOnly: "Use capital letters A–Z only (no numbers or special characters).",
    countryAdded: "Country added",
    addBankFailed: "Add bank failed",
    bankCodeLettersOnly: "Use capital letters A–Z only (no numbers or special characters).",
    bankAlreadyExists: "Bank \"{bank}\" already exists",
    bankAdded: "Bank added",
    removeCountryFailed: "Remove country failed",
    countryRemoved: "Country removed",
    currencyInUseKeepInAccountList:
      "Country removed from the list. Currency {code} is still used by accounts and remains in Other Currency.",
    removeBankFailed: "Remove bank failed",
    bankRemoved: "Bank removed",
    removeCountryConfirm: "Remove country \"{country}\" and all its banks?",
    removeBankConfirm: "Remove bank \"{bank}\" from country \"{country}\"?",
    missingCompanyContext: "Missing company context.",
    failedLoadBankProcess: "Failed to load bank process",
    dayEndEarlierThanStart: "Day end cannot be earlier than Day start",
    saveFailed: "Save failed",
    bankProcessUpdated: "Bank process updated",
    bankProcessAdded: "Bank process added",
    needOneDueItem: "Please select at least one due item",
    transactionPostFailed: "Transaction post failed",
    postedToTransaction: "Posted to transaction",
    tickDeleteRows: "Please tick rows in Delete column",
    deleteDueFailed: "Delete from due failed",
    removedFromDue: "Removed from Accounting Due",
    remarkUpdateFailed: "Remark update failed",
    remarkUpdated: "Remark updated",
    resendFailed: "Resend failed",
    resendSuccessful: "Resend successful",
    deleteFailed: "Delete failed",
    statusUpdated: "Status updated",
    statusUpdateFailed: "Status update failed",
    processDeletedOne: "1 process deleted successfully",
    processDeletedMany: "{count} processes deleted successfully",
    accountAddedSuccessfully: "Account added successfully",
    pleaseSelectCompanyFirst: "Please select a company first",
    pleaseSelectCountryFirst: "Please select Country first",
    failedCreateCurrency: "Failed to create currency",
    currencyCreated: "Currency {code} created",
    failedDeleteCurrency: "Failed to delete currency",
    paymentAlertRequired: "When Payment Alert is Yes, Alert Type and Start Date are required.",
    alertAmountNegative: "Alert Amount must be negative.",

    no: "No",
    supplier: "Supplier",
    country: "Country",
    bank: "Bank",
    types: "Types",
    cardOwner: "Card Owner",
    contract: "Contract",
    insurance: "Insurance",
    customer: "Customer",
    cost: "Cost",
    price: "Price",
    profit: "Profit",
    status: "Status",
    date: "Date",
    action: "Action",
    selectAll: "Select all",
    selectAllDeletableOnPage: "Select all deletable bank processes on this page",
    loadData: "Load the Data...",
    noProcessDataFound: "No process data found",
    edit: "Edit",
    remark: "Remark",
    resend: "Resend",
    resendToAccountingDue: "Resend to Accounting Due",
    selectForDeletion: "Select for deletion",

    editProcess: "Edit Process",
    bankInformation: "Bank Information",
    detail: "Detail",
    countryCurrency: "Country (Currency)",
    selectCountry: "Select Country",
    addNewCountry: "Add New Country",
    selectBank: "Select Bank",
    addNewBank: "Add New Bank",
    buyPrice: "Buy Price",
    sellPrice: "Sell Price",
    enterAmount: "Enter amount",
    type: "Type",
    selectType: "Select Type",
    personal: "PERSONAL",
    enterprise: "ENTERPRISE",
    business: "BUSINESS",
    enterCardOwner: "Enter Card Owner",
    dayStart: "Day start",
    dayEnd: "Day end",
    dayEndMonthlyCapTooltip:
      "When on, Day end cannot be edited; also enables day-end monthly cap (1st of Every Month).",
    dayEndRequiredForCap: "Please select a valid Day end before enabling Day-end cap.",
    companyAccount: "Company",
    autoCalculated: "Auto calculated",
    frequency: "Frequency",
    firstOfEveryMonth: "1st of Every Month",
    monthly: "Monthly",
    weekFrequency: "Week",
    dayFrequency: "Day",
    onceFrequency: "Once",
    dayEndNotUsedWhenOnce: "Not used when Frequency is Once",
    contractRequiredUnlessOnce: "Contract is required unless Frequency is Once.",
    contractRequiredUnlessOnceOrWeek: "Contract is required unless Frequency is Once, Week, or Day.",
    contractRequiredUnlessOnceWeekOrDay: "Contract is required unless Frequency is Once, Week, or Day.",
    selectedProfitSharing: "Selected Profit Sharing",
    noProfitSharingSelected: "No profit sharing selected",
    sop: "SOP",
    sopFilled: "SOP filled",
    remarkFilled: "Remark filled",
    recordSection: "Record",
    dtsModified: "DTS Modified:",
    dtsCreated: "DTS Created:",
    updateProcess: "Update Process",
    cancel: "Cancel",

    selectOrAddCountry: "Select or Add Country",
    add: "Add",
    availableCountries: "Available Countries",
    searchCountries: "Search countries...",
    searchCountriesShort: "Search countries",
    newCountryNamePlaceholder: "Enter new country name...",
    removeCountryFromCompanyListAria: "Remove {country} from company country list",
    removeSelectedCountryAria: "Remove {country} from selection",
    selectedCountries: "Selected Countries",
    none: "None",
    selectAtLeastOneCountry: "Select at least one country to add to the dropdown.",
    countryConfirmAddsToDropdownHint: "Selected items are added as Country (Currency) options; pick one in the form if you chose several.",
    confirm: "Confirm",

    selectOrAddBank: "Select or Add Bank",
    availableBanks: "Available Banks",
    searchBanks: "Search banks...",
    selectedBanks: "Selected Banks",
    selectAtLeastOneBank: "Select at least one bank on the right to add to the dropdown.",
    bankConfirmAddsToDropdownHint: "Selected items are added as Bank options; pick one in the form if you chose several.",
    selectExactlyOneBank: "Select exactly one bank on the right (add from the list or remove extras with ×).",

    addProfitSharing: "Add Profit Sharing",
    account: "Account",
    amount: "Amount",
    removeRow: "Remove row",
    addAnotherAccountAmount: "Add another Account & Amount",
    addAccountInline: "+ Add Account",

    confirmDeleteTitle: "Confirm Delete",
    confirmDeleteMessage: "Are you sure you want to delete {count} process(es)? This action cannot be undone.",
    deleting: "Deleting...",

    selectAccount: "Select Account",
    searchAccount: "Search account...",
    noAccountsFound: "No accounts found",

    resendToDueTitle: "Resend to Accounting Due",
    processLabel: "Process",
    billingSchedule: "Billing schedule",
    billingScheduleHint: "These values apply only to this Resend (which month to reopen). They are not saved to the process record; Edit Process keeps its own billing until you click Update Process.",
    resendAction: "Resend",
    resendLockedPostedToday: "This day start was already posted today. Remove it from Accounting Due or delete the bill in Maintenance to resend.",
    resendDuplicateOpenAnchor: "This process already has an open Resend bill for this day start in Accounting Due. Transaction or delete it before resending the same date.",
    resendLockChecking: "Checking…",

    notePlaceholder: "Enter notes for this process...",
    save: "Save",
    saving: "Saving...",

    deleteCol: "Delete",
    accountingDueColPost: "Post",
    accountingDueColDelete: "Delete",
    selectAllForDelete: "Select all for delete",
    startDate: "Start Date",
    billingDate: "Billing Date",
    loading: "Loading...",
    noDueToday: "No process due for accounting today.",
    refresh: "Refresh",
    close: "Close",
    accountingDueAwaiting: "{count} process awaiting accounting",
    accountingDueAwaitingPlural: "{count} processes awaiting accounting",
    transaction: "Transaction",

    errCannotDeleteWithDayStart: "Cannot delete bank process with day start set",
    errNoInactiveToDelete: "No inactive processes to delete",
    errProcessHasTransactions: "Cannot delete: process has transactions",
    errProcessLinkedToFormula: "Cannot delete: process is linked to a formula",
    errNoProcessIds: "No process IDs provided",
    errReadOnlyAccount: "Read-only account cannot perform this action",
    errNotLoggedIn: "Please log in first",
    errMissingCompany: "Company context is missing",
    errNoPermission: "No permission to operate on this process",
    errManagerRequiredForActive: "Only manager or above can change Bank Process from INACTIVE to ACTIVE",
    errInvalidProcessId: "Invalid process ID",
    errDeleteFailedGeneric: "Delete failed",
    errInvalidDateFormat: "Invalid date format (YYYY-MM-DD required)",
    errResendDuplicateToday: "This process has already been resent for this day start today. Duplicate resends are not allowed.",
    errResendDuplicateOpenAnchor: "This process already has an open Resend bill for this day start in Accounting Due. Transaction or delete it before resending the same date.",
    errResendUnrecognizedDayStart: "Cannot recognize day start. Resend only supports reopening the month of day start.",
    errResendProcessNotFound: "Bank process not found or no permission",
    errResendOnlyActive: "Only Active processes can use Resend",
    errResendBlockedStatus: "Processes with Official, E-Invoice, or Block status cannot use Resend",
    errResendSuccessDone: "Done: this process can appear in Accounting Due again.",
    errPostLoginRequired: "Please log in first",
    errPostSelectProcess: "Please select at least one process",
    errPostNoProcessesFound: "No process found to post (only active or Accounting Due items in current company)",
    errPostNotYetDue: "Not yet due; no transaction created (except Resend).",
    errPostCreatedCount: "Posted {count} transaction record(s).",
    errMethodNotAllowed: "Method not allowed",
    errInvalidRequest: "Invalid request",
    errUserNotLoggedIn: "User not logged in or company not selected",
    errStatusColumnMissing: "Status option column is missing. Please run the latest SQL update first.",
    errProcessNotFound: "Process not found or no permission",
    errDayStartCannotBeToday: "Day start cannot be the same as today",
    errDayStartSameAsContract: "Resend day start cannot use the same calendar date as the current contract day start",
    statusActive: "ACTIVE",
    statusInactive: "INACTIVE",
    statusOfficial: "OFFICIAL",
    statusEInvoice: "E-INVOICE",
    statusBlock: "BLOCK",
    toggleOn: "ON",
    toggleOff: "OFF",
    removeBankChipAria: "Remove {bank}",
  },
  zh: {
    bankProcessList: "银行流程列表",
    accountingDue: "待入账",
    addProcess: "新增流程",
    addAccount: "新增账号",
    selectDateRange: "选择日期范围",
    pickDate: "日/月/年",
    selectEndDate: "选择结束日期",
    clearDate: "清除",
    clearDateRange: "清除日期范围",
    periodShortcutsAria: "周期快捷",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    lastYear: "去年",
    monthsShort: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    weekdaysShort: ["日", "一", "二", "三", "四", "五", "六"],
    search: "搜索",
    filter: "筛选",
    filterDoubleClickClear: "双击清除筛选",
    filterClearAll: "清除全部筛选",
    showAll: "显示全部",
    showInactive: "显示停用",
    showOfficial: "显示官方",
    showEInvoice: "显示电子发票",
    showBlock: "显示封锁",
    delete: "删除",
    groupId: "集团：",
    groupFilterAll: "ALL",
    currency: "货币：",
    currencyDragHint: "拖动调整顺序 · 点击筛选",
    company: "公司：",
    pageOf: "{current} / {total}",
    readOnlyActionBlocked: "只读账号，无法执行此操作。",
    failedLoadBankProcesses: "加载银行流程失败",
    switchCompanyFailed: "切换公司失败",
    addCountryFailed: "新增国家失败",
    countryAlreadyExists: "国家「{country}」已存在",
    countryCodeLettersOnly: "仅允许大写字母 A–Z（不可含数字或特殊字符）。",
    countryAdded: "国家已新增",
    addBankFailed: "新增银行失败",
    bankCodeLettersOnly: "仅允许大写字母 A–Z（不可含数字或特殊字符）。",
    bankAlreadyExists: "银行「{bank}」已存在",
    bankAdded: "银行已新增",
    removeCountryFailed: "删除国家失败",
    countryRemoved: "国家已删除",
    currencyInUseKeepInAccountList: "已从列表移除该国家/货币，但 {code} 仍被账号使用，Other Currency 中仍会保留。",
    removeBankFailed: "删除银行失败",
    bankRemoved: "银行已删除",
    removeCountryConfirm: "删除国家“{country}”及其所有银行？",
    removeBankConfirm: "从国家“{country}”删除银行“{bank}”？",
    missingCompanyContext: "缺少公司上下文。",
    failedLoadBankProcess: "加载银行流程失败",
    dayEndEarlierThanStart: "结束日期不能早于开始日期",
    saveFailed: "保存失败",
    bankProcessUpdated: "银行流程已更新",
    bankProcessAdded: "银行流程已新增",
    needOneDueItem: "请至少选择一条待入账数据",
    transactionPostFailed: "入账失败",
    postedToTransaction: "已发送到交易",
    tickDeleteRows: "请勾选删除列中的行",
    deleteDueFailed: "从待入账删除失败",
    removedFromDue: "已从待入账移除",
    remarkUpdateFailed: "备注更新失败",
    remarkUpdated: "备注已更新",
    resendFailed: "重发失败",
    resendSuccessful: "重发成功",
    deleteFailed: "删除失败",
    statusUpdated: "状态已更新",
    statusUpdateFailed: "状态更新失败",
    processDeletedOne: "已成功删除 1 条流程",
    processDeletedMany: "已成功删除 {count} 条流程",
    accountAddedSuccessfully: "账号新增成功",
    pleaseSelectCompanyFirst: "请先选择公司",
    pleaseSelectCountryFirst: "请先选择国家",
    failedCreateCurrency: "创建货币失败",
    currencyCreated: "货币 {code} 已创建",
    failedDeleteCurrency: "删除货币失败",
    paymentAlertRequired: "当 Payment Alert 为 Yes 时，Alert Type 和 Start Date 为必填。",
    alertAmountNegative: "Alert Amount 必须为负数。",

    no: "序号",
    supplier: "供应商",
    country: "国家",
    bank: "银行",
    types: "类型",
    cardOwner: "卡主",
    contract: "合同",
    insurance: "保险",
    customer: "客户",
    cost: "成本",
    price: "售价",
    profit: "利润",
    status: "状态",
    date: "日期",
    action: "操作",
    selectAll: "全选",
    selectAllDeletableOnPage: "全选本页可删除银行流程",
    loadData: "加载数据中...",
    noProcessDataFound: "未找到流程数据",
    edit: "编辑",
    remark: "备注",
    resend: "重发",
    resendToAccountingDue: "重发到待入账",
    selectForDeletion: "勾选删除",

    editProcess: "编辑流程",
    bankInformation: "银行信息",
    detail: "详情",
    countryCurrency: "国家（货币）",
    selectCountry: "选择国家",
    addNewCountry: "新增国家",
    selectBank: "选择银行",
    addNewBank: "新增银行",
    buyPrice: "买价",
    sellPrice: "卖价",
    enterAmount: "输入金额",
    type: "类型",
    selectType: "选择类型",
    personal: "个人",
    enterprise: "企业",
    business: "商业",
    enterCardOwner: "输入卡主",
    dayStart: "起始日",
    dayEnd: "结束日",
    dayEndMonthlyCapTooltip:
      "开启后，结束日不可编辑，并启用月末封顶（每月 1 日频率）。",
    dayEndRequiredForCap: "启用月末封顶前请先选择有效的结束日。",
    companyAccount: "公司",
    autoCalculated: "自动计算",
    frequency: "频率",
    firstOfEveryMonth: "每月1号",
    monthly: "按月",
    weekFrequency: "按周",
    dayFrequency: "按天",
    onceFrequency: "一次性",
    dayEndNotUsedWhenOnce: "Frequency 为「一次性」时不使用结束日",
    contractRequiredUnlessOnce: "除 Frequency 为「一次性」外，合同为必填。",
    contractRequiredUnlessOnceOrWeek: "除 Frequency 为「一次性」「按周」或「按天」外，合同为必填。",
    contractRequiredUnlessOnceWeekOrDay: "除 Frequency 为「一次性」「按周」或「按天」外，合同为必填。",
    selectedProfitSharing: "已选利润分成",
    noProfitSharingSelected: "未选择利润分成",
    sop: "SOP",
    sopFilled: "已填写 SOP",
    remarkFilled: "已填写备注",
    recordSection: "记录",
    dtsModified: "修改时间：",
    dtsCreated: "创建时间：",
    updateProcess: "更新流程",
    cancel: "取消",

    selectOrAddCountry: "选择或新增国家",
    add: "新增",
    availableCountries: "可用国家",
    searchCountries: "搜索国家...",
    searchCountriesShort: "搜索国家",
    newCountryNamePlaceholder: "输入新国家/货币代码...",
    removeCountryFromCompanyListAria: "从公司列表删除 {country}",
    removeSelectedCountryAria: "从已选中移除 {country}",
    selectedCountries: "已选国家",
    none: "无",
    selectAtLeastOneCountry: "请至少选择一个国家以加入下拉选项。",
    countryConfirmAddsToDropdownHint: "已选项会加入「国家（货币）」下拉里；若选了多个，请在表单中再选一个。",
    confirm: "确认",

    selectOrAddBank: "选择或新增银行",
    availableBanks: "可用银行",
    searchBanks: "搜索银行...",
    selectedBanks: "已选银行",
    selectAtLeastOneBank: "请至少在右侧选择一个银行以加入下拉选项。",
    bankConfirmAddsToDropdownHint: "已选项会加入「银行」下拉里；若选了多个，请在表单中再选一个。",
    selectExactlyOneBank: "请在右侧仅保留一个银行（可从左侧添加，或用 × 删除多余项）。",

    addProfitSharing: "新增利润分成",
    account: "账号",
    amount: "金额",
    removeRow: "删除行",
    addAnotherAccountAmount: "新增一行账号与金额",
    addAccountInline: "+ 添加账号",

    confirmDeleteTitle: "确认删除",
    confirmDeleteMessage: "确定删除 {count} 条流程吗？此操作不可撤销。",
    deleting: "删除中...",

    selectAccount: "选择账号",
    searchAccount: "搜索账号...",
    noAccountsFound: "未找到账号",

    resendToDueTitle: "重发到待入账",
    processLabel: "流程",
    billingSchedule: "账单计划",
    billingScheduleHint: "这些值仅用于本次重发（决定重开月份），不会保存到流程记录；如需长期生效，请在 Edit Process 里点击 Update Process。",
    resendAction: "重发",
    resendLockedPostedToday: "该起始日今日已入账。请从待入账删除，或在维护中删除对应账单后再重发。",
    resendDuplicateOpenAnchor: "该流程在待入账中已有相同起始日的重发账单。请先入账或删除后再重发同一日期。",
    resendLockChecking: "检查中…",

    notePlaceholder: "输入该流程备注...",
    save: "保存",
    saving: "保存中...",

    deleteCol: "删除",
    accountingDueColPost: "入账",
    accountingDueColDelete: "删除",
    selectAllForDelete: "全选删除",
    startDate: "开始日期",
    billingDate: "账单日期",
    loading: "加载中...",
    noDueToday: "今天没有待入账流程。",
    refresh: "刷新",
    close: "关闭",
    accountingDueAwaiting: "{count} 条流程待入账",
    accountingDueAwaitingPlural: "{count} 条流程待入账",
    transaction: "入账",

    errCannotDeleteWithDayStart: "已设置起始日的银行流程无法删除",
    errNoInactiveToDelete: "没有可删除的停用流程",
    errProcessHasTransactions: "无法删除：该流程已有交易记录",
    errProcessLinkedToFormula: "无法删除：该流程已关联公式",
    errNoProcessIds: "未提供流程 ID",
    errReadOnlyAccount: "只读账号无法执行此操作",
    errNotLoggedIn: "请先登录",
    errMissingCompany: "缺少公司信息",
    errNoPermission: "无权限操作此流程",
    errManagerRequiredForActive: "仅经理及以上可将银行流程从停用改为启用",
    errInvalidProcessId: "无效的流程 ID",
    errDeleteFailedGeneric: "删除失败",
    errInvalidDateFormat: "日期格式无效（需 YYYY-MM-DD）",
    errResendDuplicateToday: "该流程今日已对此起始日重发，不允许重复重发。",
    errResendDuplicateOpenAnchor: "该流程在待入账中已有相同起始日的重发账单。请先入账或删除后再重发同一日期。",
    errResendUnrecognizedDayStart: "无法识别起始日，重发仅支持按起始日当月补单月记录。",
    errResendProcessNotFound: "未找到该银行流程或无权操作",
    errResendOnlyActive: "仅状态为启用的流程可使用重发",
    errResendBlockedStatus: "官方、电子发票、封锁状态的流程不可使用重发",
    errResendSuccessDone: "完成：该流程可再次出现在待入账中。",
    errPostLoginRequired: "请先登录",
    errPostSelectProcess: "请至少选择一个流程",
    errPostNoProcessesFound: "未找到可入账的流程（仅处理当前公司下启用或待入账中的流程）",
    errPostNotYetDue: "未到应付日，暂不生成交易记录（重发除外）。",
    errPostCreatedCount: "已入账，共生成 {count} 条交易记录。",
    errMethodNotAllowed: "不允许的请求方法",
    errInvalidRequest: "无效的请求",
    errUserNotLoggedIn: "用户未登录或未选择公司",
    errStatusColumnMissing: "缺少状态选项字段，请先执行最新 SQL 更新。",
    errProcessNotFound: "未找到流程或无权限",
    errDayStartCannotBeToday: "起始日不可与今天相同",
    errDayStartSameAsContract: "重填的起始日不可与当前合同起始日为同一日历日",
    statusActive: "启用",
    statusInactive: "停用",
    statusOfficial: "官方",
    statusEInvoice: "电子发票",
    statusBlock: "封锁",
    toggleOn: "开",
    toggleOff: "关",
    removeBankChipAria: "移除 {bank}",
  },
};

const API_ERROR_CODE_KEYS = {
  bank_has_day_start: "errCannotDeleteWithDayStart",
  no_inactive_processes: "errNoInactiveToDelete",
  process_has_transactions: "errProcessHasTransactions",
  process_linked_to_formula: "errProcessLinkedToFormula",
};

function normApiMessage(s) {
  return String(s || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ")
    .replace(/[.!?]+$/g, "");
}

const API_MESSAGE_KEYS = {
  [normApiMessage("Cannot delete bank process with day_start set")]: "errCannotDeleteWithDayStart",
  [normApiMessage("Cannot delete bank process with day start set")]: "errCannotDeleteWithDayStart",
  [normApiMessage("No inactive processes to delete")]: "errNoInactiveToDelete",
  [normApiMessage("Process has transactions")]: "errProcessHasTransactions",
  [normApiMessage("Process linked to formula")]: "errProcessLinkedToFormula",
  [normApiMessage("No process IDs provided")]: "errNoProcessIds",
  [normApiMessage("Read-only account cannot perform this action")]: "errReadOnlyAccount",
  [normApiMessage("只读账号无法执行此操作")]: "errReadOnlyAccount",
  [normApiMessage("User not logged in or company not selected")]: "errUserNotLoggedIn",
  [normApiMessage("Please log in first")]: "errNotLoggedIn",
  [normApiMessage("请先登录")]: "errNotLoggedIn",
  [normApiMessage("Company not found in session")]: "errMissingCompany",
  [normApiMessage("缺少公司信息")]: "errMissingCompany",
  [normApiMessage("Missing company context")]: "errMissingCompany",
  [normApiMessage("无权限操作此流程")]: "errNoPermission",
  [normApiMessage("No permission to operate on this process")]: "errNoPermission",
  [normApiMessage("Process not found or no permission")]: "errProcessNotFound",
  [normApiMessage("Only manager or above can change Bank Process from INACTIVE to ACTIVE")]: "errManagerRequiredForActive",
  [normApiMessage("Invalid process ID")]: "errInvalidProcessId",
  [normApiMessage("无效的流程ID")]: "errInvalidProcessId",
  [normApiMessage("无效的 Process ID")]: "errInvalidProcessId",
  [normApiMessage("Delete failed")]: "errDeleteFailedGeneric",
  [normApiMessage("Method not allowed")]: "errMethodNotAllowed",
  [normApiMessage("Invalid request method")]: "errMethodNotAllowed",
  [normApiMessage("只支持 POST 请求")]: "errMethodNotAllowed",
  [normApiMessage("无效的请求数据")]: "errInvalidRequest",
  [normApiMessage("日期格式无效（需 YYYY-MM-DD）")]: "errInvalidDateFormat",
  [normApiMessage("Day end 不能早于 Day start")]: "dayEndEarlierThanStart",
  [normApiMessage("Day end cannot be earlier than Day start")]: "dayEndEarlierThanStart",
  [normApiMessage("无法识别 Day start，Resend 仅支持按 Day start 当月补单月记录。")]: "errResendUnrecognizedDayStart",
  [normApiMessage("This process has already been resent for this Day start today. Duplicate resends are not allowed.")]: "errResendDuplicateToday",
  [normApiMessage("This process already has an open Resend bill for this Day start in Accounting Due. Transaction or delete it before resending the same date.")]: "errResendDuplicateOpenAnchor",
  [normApiMessage("未找到该 Bank Process 或无权操作")]: "errResendProcessNotFound",
  [normApiMessage("仅状态为 Active 的 Process 可使用 Resend")]: "errResendOnlyActive",
  [normApiMessage("Official、E-INVOICE、Block 状态的 Process 不可使用 Resend")]: "errResendBlockedStatus",
  [normApiMessage("Done: This process can appear in Accounting Due again.")]: "errResendSuccessDone",
  [normApiMessage("请至少选择一个 Process")]: "errPostSelectProcess",
  [normApiMessage("未找到可入账的 Process（仅处理当前公司下 active 或 Accounting Due 中的 Process）")]: "errPostNoProcessesFound",
  [normApiMessage("未到应付日，暂不生成交易记录（Resend 除外）。")]: "errPostNotYetDue",
  [normApiMessage("Posted to transaction")]: "postedToTransaction",
  [normApiMessage("Removed from Accounting Due")]: "removedFromDue",
  [normApiMessage("1 process deleted")]: "processDeletedOne",
  [normApiMessage("Resend successful")]: "resendSuccessful",
  [normApiMessage("Resend failed")]: "resendFailed",
  [normApiMessage("Status updated")]: "statusUpdated",
  [normApiMessage("Status update failed")]: "statusUpdateFailed",
  [normApiMessage("Failed to update status option")]: "statusUpdateFailed",
};

function messageLanguageHint(s) {
  const text = String(s || "");
  const hasCjk = /[\u4e00-\u9fff]/.test(text);
  const hasLatin = /[a-zA-Z]/.test(text);
  if (hasCjk && !hasLatin) return "zh";
  if (hasLatin && !hasCjk) return "en";
  return "mixed";
}

function translateDynamicApiMessage(lang, message) {
  const raw = String(message || "").trim();
  if (!raw) return null;

  let m = raw.match(/^(\d+)\s+process(?:es)?\s+deleted$/i);
  if (m) {
    const count = Number(m[1]);
    return getBankProcessText(lang, count === 1 ? "processDeletedOne" : "processDeletedMany", { count });
  }

  m = raw.match(/已入账，共生成\s*(\d+)\s*条交易记录/);
  if (m) return getBankProcessText(lang, "errPostCreatedCount", { count: m[1] });

  m = raw.match(/posted\s+(\d+)\s+transaction/i);
  if (m) return getBankProcessText(lang, "errPostCreatedCount", { count: m[1] });

  if (/day\s*start\s+cannot\s+be\s+today/i.test(raw) || raw.includes("不可与今天相同")) {
    return getBankProcessText(lang, "errDayStartCannotBeToday");
  }
  if (/same\s+calendar\s+date\s+as\s+the\s+current\s+contract\s+day\s+start/i.test(raw) || raw.includes("Resend 所填 Day start")) {
    return getBankProcessText(lang, "errDayStartSameAsContract");
  }
  if (/bank_process\.flag|issue_flag\s+column\s+is\s+missing/i.test(raw)) {
    return getBankProcessText(lang, "errStatusColumnMissing");
  }
  if (/failed\s+to\s+update\s+status\s+option/i.test(raw)) {
    return getBankProcessText(lang, "statusUpdateFailed");
  }

  return null;
}

/**
 * Map backend API message / error code to bank-process i18n for toasts and inline errors.
 */
export function translateBankProcessApiMessage(lang, payload, fallback = "") {
  const message = String(payload?.message ?? payload ?? "").trim();
  const errorCode = payload?.errorCode ?? payload?.error_code;
  const locale = lang === "zh" ? "zh" : "en";

  if (errorCode && API_ERROR_CODE_KEYS[errorCode]) {
    return getBankProcessText(locale, API_ERROR_CODE_KEYS[errorCode]);
  }

  const dynamic = translateDynamicApiMessage(locale, message);
  if (dynamic) return dynamic;

  const key = API_MESSAGE_KEYS[normApiMessage(message)];
  if (key) return getBankProcessText(locale, key);

  const hint = messageLanguageHint(message);
  if (message && hint !== "mixed" && hint !== locale && fallback) return fallback;

  return message || fallback;
}

export function getBankProcessLocale(lang) {
  return BANK_PROCESS_I18N[toLocale(lang)] ?? BANK_PROCESS_I18N.en;
}

export function getBankProcessText(lang, key, params = {}) {
  const locale = toLocale(lang);
  const template = BANK_PROCESS_I18N[locale][key] ?? BANK_PROCESS_I18N.en[key] ?? key;
  if (typeof template !== "string") return template;
  return interpolate(template, params);
}
