import { createGetText } from "../shared/i18nHelpers.js";

export const DATA_CAPTURE_SUMMARY_I18N = {
  en: {
    pageTitle: "Data Capture Summary",
    loading: "Loading…",
    loadingData: "Loading data...",
    loadPageFailed: "Failed to load Data Capture Summary. Please refresh the page or return to Data Capture.",
    rate: "Rate",
    ratePlaceholder: "e.g. *3 or /3",
    selectAll: "Select All",
    clearAll: "Clear All",
    submit: "Submit",
    submitting: "Submitting...",
    delete: "Delete",
    deleteWithCount: "Delete ({count})",
    deleteSelectedRows: "Delete selected rows",
    back: "Back",
    refresh: "Refresh",
    refreshPage: "Refresh page",
    cancel: "Cancel",
    confirmDelete: "Confirm Delete",
    date: "Date:",
    process: "Process:",
    description: "Description:",
    currency: "Currency:",
    currencyColumn: "Currency",
    remark: "Remark:",
    idProduct: "Id Product",
    account: "Account",
    formula: "Formula",
    source: "Source",
    rateValue: "Rate Value",
    processedAmount: "Processed Amount",
    skip: "Skip",
    noCapturedData: "No Captured Data Available",
    emptyStateHint: "No captured data found. Please go back to the Data Capture page and submit some data first.",
    goToDataCapture: "Go to Data Capture",
    editFormula: "Edit Formula",
    close: "Close",
    selectAccount: "Select Account",
    searchAccount: "Search account...",
    addNewAccount: "Add New Account",
    sourcePercentPlaceholder: "e.g. 1 or 2 or 0.5 (multiplier)",
    data: "Data",
    selectIdProduct: "Select Id Product",
    selectRowData: "Select Row Data",
    addSelectedDataToFormula: "Add Selected Data To Formula",
    add: "Add",
    formulaPlaceholder: "e.g. $5+$10*0.6/7",
    inputMethod: "Input Method",
    selectInputMethod: "Select Input Method (Optional)",
    selectCurrency: "Select Currency",
    save: "Save",
    saving: "Saving...",
    calcClear: "Clr",
    inputMethod_positive_to_negative_negative_to_positive: "Positive to negative, negative to positive",
    inputMethod_positive_to_negative_negative_to_zero: "Positive to negative, negative to zero",
    inputMethod_negative_to_positive_positive_to_zero: "Negative to positive, positive to zero",
    inputMethod_positive_unchanged_negative_to_zero: "Positive unchanged, negative to zero",
    inputMethod_negative_unchanged_positive_to_zero: "Negative unchanged, positive to zero",
    inputMethod_change_to_positive: "Change to positive",
    inputMethod_change_to_negative: "Change to negative",
    inputMethod_change_to_zero: "Change to zero",
    notifSuccess: "Success",
    notifError: "Error",
    notifWarning: "Warning",
    notifInfo: "Info",
    captureGeneratedSuccess: "Data captured and summary generated successfully!",
    captureGeneratedFailed: "Failed to generate summary. Please try again.",
    readOnlyBlocked: "Read-only account: this action is not allowed.",
    noProcessData: "No process data found. Please return to Data Capture page.",
    totalValidationFailed: "Total validation failed.",
    prepareRowsFailed: "Failed to prepare summary rows.",
    submissionFailed: "Submission failed.",
    deleteInvalidRows: "Please select valid rows to delete. Empty sub rows cannot be deleted.",
    deleteConfirm: "Are you sure you want to delete {count} selected row(s)? This action cannot be undone.",
    rateInputNotFound: "Rate input field not found",
    pleaseEnterRate: "Please enter a Rate value",
    summaryTableNotFound: "Summary table not found",
    rateUpdated: "Rate Value updated for {count} row(s)",
    noRateRowsChecked: "No rows with Rate checkbox checked",
    selectedRateRows: "Selected {count} row(s) with Rate",
    clearedRateRows: "Cleared Rate selection for {count} row(s)",
    batchSourceColumns: "Source Columns",
    batchSourceColumnsPlaceholder: "e.g. 5+4",
    batchSourceEmpty: "Please enter source columns (e.g. 5+4)",
    batchSourceInvalid: "Invalid format. Please use format like: 5+4 or 3-2+1 or (5+4)",
    batchSourceUpdated: "Updated {count} row(s) successfully!",
    batchSourceNoRows: "No rows with data were found",
    rowsDeleted: "{count} row(s) deleted successfully!",
    formulaSaved: "Formula saved.",
    confirmDeleteRows: "Are you sure you want to delete {count} selected row(s)? This action cannot be undone.",
    enterRateValue: "Please enter a Rate value",
  },
  zh: {
    pageTitle: "数据采集汇总",
    loading: "加载中…",
    loadingData: "加载数据中...",
    loadPageFailed: "数据采集汇总加载失败，请刷新页面或返回数据采集页。",
    rate: "倍率",
    ratePlaceholder: "例如 *3 或 /3",
    selectAll: "全选",
    clearAll: "清空",
    submit: "提交",
    submitting: "提交中...",
    delete: "删除",
    deleteWithCount: "删除（{count}）",
    deleteSelectedRows: "删除所选行",
    back: "返回",
    refresh: "刷新",
    refreshPage: "刷新页面",
    cancel: "取消",
    confirmDelete: "确认删除",
    date: "日期：",
    process: "流程：",
    description: "描述：",
    currency: "货币：",
    currencyColumn: "货币",
    remark: "备注：",
    idProduct: "产品 Id",
    account: "账户",
    formula: "公式",
    source: "来源",
    rateValue: "倍率值",
    processedAmount: "处理金额",
    skip: "跳过",
    noCapturedData: "暂无采集数据",
    emptyStateHint: "未找到采集数据。请先返回数据采集页提交数据。",
    goToDataCapture: "前往数据采集",
    editFormula: "编辑公式",
    close: "关闭",
    selectAccount: "选择账户",
    searchAccount: "搜索账户…",
    addNewAccount: "新增账户",
    sourcePercentPlaceholder: "例如 1 或 2 或 0.5（倍数）",
    data: "数据",
    selectIdProduct: "选择产品 Id",
    selectRowData: "选择行数据",
    addSelectedDataToFormula: "将所选数据加入公式",
    add: "添加",
    formulaPlaceholder: "例如 $5+$10*0.6/7",
    inputMethod: "输入方式",
    selectInputMethod: "选择输入方式（可选）",
    selectCurrency: "选择货币",
    save: "保存",
    saving: "保存中...",
    calcClear: "清除",
    inputMethod_positive_to_negative_negative_to_positive: "正转负，负转正",
    inputMethod_positive_to_negative_negative_to_zero: "正转负，负转零",
    inputMethod_negative_to_positive_positive_to_zero: "负转正，正转零",
    inputMethod_positive_unchanged_negative_to_zero: "正不变，负转零",
    inputMethod_negative_unchanged_positive_to_zero: "负不变，正转零",
    inputMethod_change_to_positive: "改为正数",
    inputMethod_change_to_negative: "改为负数",
    inputMethod_change_to_zero: "改为零",
    notifSuccess: "成功",
    notifError: "错误",
    notifWarning: "警告",
    notifInfo: "提示",
    captureGeneratedSuccess: "数据采集成功，汇总已生成！",
    captureGeneratedFailed: "生成汇总失败，请重试。",
    readOnlyBlocked: "只读账号，无法执行此操作。",
    noProcessData: "未找到流程数据，请返回数据采集页。",
    totalValidationFailed: "合计校验失败。",
    prepareRowsFailed: "准备汇总行失败。",
    submissionFailed: "提交失败。",
    deleteInvalidRows: "请选择有效的行删除，空的 sub 行不能删除。",
    deleteConfirm: "确认删除所选 {count} 行吗？此操作无法撤销。",
    rateInputNotFound: "未找到 Rate 输入框",
    pleaseEnterRate: "请输入 Rate 值",
    summaryTableNotFound: "未找到汇总表",
    rateUpdated: "已更新 {count} 行的 Rate Value",
    noRateRowsChecked: "没有勾选 Rate 的行",
    selectedRateRows: "已勾选 {count} 行的 Rate",
    clearedRateRows: "已取消 {count} 行的 Rate 勾选",
    batchSourceColumns: "来源列",
    batchSourceColumnsPlaceholder: "例如 5+4",
    batchSourceEmpty: "请输入来源列（例如 5+4）",
    batchSourceInvalid: "格式无效。请使用例如：5+4 或 3-2+1 或 (5+4)",
    batchSourceUpdated: "已成功更新 {count} 行！",
    batchSourceNoRows: "未找到有数据的行",
    rowsDeleted: "已成功删除 {count} 行！",
    formulaSaved: "公式已保存。",
    confirmDeleteRows: "确定要删除所选的 {count} 行吗？此操作无法撤销。",
    enterRateValue: "请输入倍率值",
  },
};

export const getDataCaptureSummaryText = createGetText(DATA_CAPTURE_SUMMARY_I18N);

const NOTIF_TITLE_KEYS = {
  Success: "notifSuccess",
  Error: "notifError",
  Warning: "notifWarning",
  Info: "notifInfo",
  成功: "notifSuccess",
  错误: "notifError",
  警告: "notifWarning",
  提示: "notifInfo",
};

const NOTIF_MESSAGE_PATTERNS = [
  { re: /^Data captured and summary generated successfully!?$/, key: "captureGeneratedSuccess" },
  { re: /^Failed to generate summary\. Please try again\.?$/, key: "captureGeneratedFailed" },
  { re: /^Read-only account: this action is not allowed\.?$/, key: "readOnlyBlocked" },
  { re: /^Rate input field not found$/, key: "rateInputNotFound" },
  { re: /^Please enter a Rate value$/, key: "pleaseEnterRate" },
  { re: /^Summary table not found$/, key: "summaryTableNotFound" },
  { re: /^Rate Value updated for (\d+) row\(s\)$/, key: "rateUpdated", count: 1 },
  { re: /^No rows with Rate checkbox checked$/, key: "noRateRowsChecked" },
  { re: /^Selected (\d+) row\(s\) with Rate$/, key: "selectedRateRows", count: 1 },
  { re: /^Cleared Rate selection for (\d+) row\(s\)$/, key: "clearedRateRows", count: 1 },
  { re: /^Cleared (\d+) row\(s\) from Rate$/, key: "clearedRateRows", count: 1 },
  { re: /^No process data found\. Please return to Data Capture page\.?$/, key: "noProcessData" },
  { re: /^Please select valid rows to delete\. Empty sub rows cannot be deleted\.?$/, key: "deleteInvalidRows" },
];

export function translateDataCaptureSummaryNotification(lang, title, message) {
  const t = (key, params) => getDataCaptureSummaryText(lang, key, params);
  const titleKey = NOTIF_TITLE_KEYS[String(title || "").trim()];
  const nextTitle = titleKey ? t(titleKey) : title;

  const rawMessage = String(message || "").trim();
  if (!rawMessage) return { title: nextTitle, message: rawMessage };

  for (const pattern of NOTIF_MESSAGE_PATTERNS) {
    const match = rawMessage.match(pattern.re);
    if (match) {
      const params = pattern.count ? { count: match[pattern.count] } : {};
      return { title: nextTitle, message: t(pattern.key, params) };
    }
  }

  return { title: nextTitle, message: rawMessage };
}

export function getSummaryInputMethodLabel(lang, value) {
  if (!value) return getDataCaptureSummaryText(lang, "selectInputMethod");
  const key = `inputMethod_${value}`;
  const text = getDataCaptureSummaryText(lang, key);
  return text === key ? value : text;
}

export function getSummaryRateSelectLabels(lang) {
  return {
    selectAll: getDataCaptureSummaryText(lang, "selectAll"),
    clearAll: getDataCaptureSummaryText(lang, "clearAll"),
  };
}
