import { createGetText } from "../shared/i18nHelpers.js";

export const DOMAIN_I18N = {
  en: {
    pleaseEnterCompanyId: "Please enter a company ID",
    companyIdAlreadyAdded: "Company ID already added",
    cannotAddGroupUsesCompanyId:
      '"{id}" is already a Company ID. Use a different Group ID.',
    cannotAddCompanyUsesGroupId:
      '"{id}" is already a Group ID. Use a different Company ID or rename/remove that group.',
    groupCompanyIdOverlapSave:
      'Cannot save — "{id}" is used as both Group ID and Company ID. Rename or remove one.',
    pleaseEnterGroupId: "Please enter a Group ID",
    groupIdAlreadyExists: "Group ID already exists",
    groupAdded: 'Group "{gid}" added!',
    confirmDeleteGroupWithCount: 'Are you sure you want to delete group "{gid}"?\n\n{count} company(ies) in this group will become ungrouped.',
    confirmDeleteGroup: 'Are you sure you want to delete group "{gid}"?',
    confirmDeleteCompany:
      'Remove company "{cid}" from this domain?\n\nIf it has accounts or Transaction Payment data, it will be detached only — all ledger data stays in the database.\nUnused companies with no data are removed permanently.',
    companyRemovedFromForm: 'Company "{cid}" removed from the form. Confirm to detach (keeps ledger) or delete if unused.',
    cannotRemoveC168Company: "Company C168 cannot be removed.",
    groupRemoved: 'Group "{gid}" removed',
    pleaseSelectGroupFirst: "Please select a Group first",
    invalidEmailFormat: "Please enter a valid email address",
    ownerUpdated: "Owner updated successfully!",
    ownerCreated: "Owner created successfully!",
    operationFailed: "Operation failed",
    validateDomainCodeUnavailable:
      "Could not verify whether this ID is available. Check your connection and try again.",
    saveOwnerError: "An error occurred while saving owner",
    noUngroupedCompaniesAvailable: "No ungrouped companies available",
    noCompaniesInGroup: 'No companies in group "{gid}". Click "Multiple Choice" to assign.',
    noUngroupedCompanies: "No ungrouped companies",
    notSet: "Not set",
    setExpirationDate: "Set expiration date",
    set: "Set",
    remove: "Remove",
    editDomain: "EDIT DOMAIN",
    addDomain: "ADD DOMAIN",
    domainInformation: "DOMAIN INFORMATION",
    companyInformation: "COMPANY INFORMATION",
    ownerCode: "Owner Code",
    name: "Name",
    email: "Email",
    password: "Password",
    showPassword: "Show password",
    hidePassword: "Hide password",
    secondaryPassword: "Secondary Password",
    leaveEmptyKeepCurrentPassword: "Leave empty to keep current password",
    sixDigitsOnly: "6 digits only",
    secondaryPwdRequirement: "Must be exactly 6 digits (0-9)",
    groupIdPlaceholder: "GROUP ID",
    add: "Add",
    companyIdPlaceholder: "COMPANY ID",
    groupIdLabel: "Group ID",
    companyIdLabel: "Company ID",
    companyPanelAddHeading: "ADD GROUP OR COMPANY",
    groupsSectionLabel: "Groups",
    selectedCompaniesHint: "Select a group tag to filter. Use Multiple Choice to assign companies to that group.",
    groupLabel: "Group :",
    noGroupsCreated: "No groups created",
    selectedGroups: "Selected Groups :",
    noGroupsAddedYet: "No groups added yet",
    groupSettings: "GROUP SETTINGS",
    groupSettingsLower: "Group settings",
    groupPrefix: "Group: ",
    renameIdLabel: "Rename ID",
    renameIdPlaceholder: "Enter new ID",
    cannotRenameToC168: "Cannot rename to C168",
    cannotRenameC168: "C168 cannot be renamed",
    groupUpdatedShareAfterSave: "Group settings updated. Share % will apply after you save the domain.",
    groupUpdatedSuccess: "Group settings updated successfully!",
    selectedCompanies: "Selected Companies :",
    done: "Done ✓",
    doneCompact: "Done",
    multipleChoice: "Multiple Choice",
    searchCompanyPlaceholder: "Search Company…",
    selectAll: "Select All",
    noCompaniesAddedYet: "No companies added yet",
    confirm: "Confirm",
    cancel: "Cancel",
    failedToLoadDomainData: "Failed to load domain data",
    feeSummary: "Display: Price {price}",
    groupPrice: "Group Price",
    companyPrice: "Company Price",
    feeInlineSummary: "Group {group} · Company {company}",
    feeChipCompanyAria: "Company domain fee, 6 months and 1 year",
    feeChipGroupAria: "Group domain fee, 6 months and 1 year",
    selectOwnersToDeleteFirst: "Please select owners to delete first",
    cannotDeleteC168Owners: "Cannot delete owners linked to company C168",
    c168OwnersCannotDeleteOthersWillDelete: "Owners linked to company C168 cannot be deleted. {count} other owner(s) will be deleted.",
    confirmDeleteOwners: "Are you sure you want to delete the following {count} owner(s)?\n\n{names}",
    deletedOwnersSuccess: "Successfully deleted {ok} owners!",
    deletionCompleted: "Deletion completed: {ok} succeeded, {fail} failed",
    batchDeleteError: "An error occurred during batch deletion",
    domainList: "Domain List",
    addDomainBtn: "Add Domain",
    searchPlaceholder: "Search by Owner Name/Company",
    price: "Price",
    deleteWithCount: "Delete ({count})",
    delete: "Delete",
    no: "No:",
    ownerCodeWithColon: "Owner Code:",
    nameWithColon: "Name:",
    emailWithColon: "Email:",
    companiesWithColon: "Companies:",
    createdBy: "Created By:",
    action: "Action:",
    edit: "Edit",
    selectOwnerForDelete: "Select owner for deletion",
    paginationOf: "{page} of {total}",
    loadAccountFormFailed: "Failed to load account form data.",
    pleaseEnterCurrencyCode: "Please enter currency code",
    currencyExists: "Currency {code} already exists",
    createCurrencyFailed: "Failed to create currency",
    currencyCreatedSuccess: "Currency {code} created successfully",
    confirmDeleteCurrency: "Are you sure you want to permanently delete currency {code}? This action cannot be undone.",
    deleteCurrencyFailed: "Failed to delete currency",
    deleteCurrencySuccess: "Currency {code} deleted successfully!",
    addAccountFailed: "Failed to add account",
    addAccountSuccess: "Account added successfully.",
    addAccountTitle: "Add Account",
    personalInformation: "Personal Information",
    accountId: "Account ID",
    role: "Role",
    selectRole: "Select Role",
    payment: "Payment",
    paymentAlert: "Payment Alert",
    yes: "Yes",
    noWord: "No",
    alertType: "Alert Type",
    selectType: "Select Type",
    weekly: "Weekly",
    monthly: "Monthly",
    days: "{n} Days",
    startDate: "Start Date",
    pickDate: "Pick date",
    clearDate: "Clear",
    alertAmount: "Alert (Amount)",
    enterAmount: "Enter amount",
    remark: "Remark",
    advancedAccount: "Advanced Account",
    otherCurrency: "Other Currency:",
    newCurrencyPlaceholder: "Enter new currency code (e.g., USD)",
    createCurrency: "Create Currency",
    noCurrenciesAvailable: "No currencies available.",
    deleteCurrencyPermanently: "Delete currency permanently",
    companyLabel: "Company:",
    addAccountBtn: "Add Account",
    companySettings: "Company Settings",
    companySettingsLower: "Company settings",
    companyPrefix: "Company: ",
    cannotModifyStartDateWhenExtending: "Cannot modify start date when extending time",
    selectStartDateHint: "Select the start date for calculating expiration date",
    period: "Period",
    selectPeriod: "Select Period",
    sevenDays: "7 Days",
    oneMonth: "1 Month",
    threeMonths: "3 Months",
    sixMonths: "6 Months",
    oneYear: "1 Year",
    expirationDate: "Expiration Date",
    permissionsLabel: "Permissions (for Process List & Data Capture)",
    permissionsHintLine: "Select which options this company can access in Process List and Data Capture pages.",
    share: "Share %",
    on: "On",
    off: "Off",
    account: "Account",
    total: "Total",
    oneAccount: "1 account",
    accountCount: "{count} accounts",
    shareTotal: "Share total",
    manage: "Manage",
    addNewAccount: "Add New Account",
    removeRow: "Remove row",
    addAccountInline: "+ Add Account",
    noLinkedAccounts: "No linked accounts.",
    save: "Save",
    saving: "Saving...",
    reset: "Reset",
    pleaseSelectOneCategory: "Please select one category",
    onlyOneCategoryAtTime: "Only one category can be selected at a time",
    permissionsSaveFailed: "Permissions save failed",
    companyUpdatedShareAfterSave: "Company settings updated. Share % will apply after you save the domain.",
    shareSaveFailed: "Share % save failed",
    feePostsHint: " Fee posts when you Confirm the domain (main modal).",
    companyShareChargeAria: "Charge when domain is confirmed",
    companyUpdatedSuccess: "Company settings updated successfully!",
    commissionSettings: "Commission Settings",
    commissionSettingsSaved: "Commission settings saved.",
    serverUnreachableChangesKept: "Could not reach server. Changes kept locally — try again.",
    couldNotLoadSettings: "Could not load settings",
    saved: "Saved",
    saveFailed: "Save failed",
    priceDescription: "Set default amounts for each period (saved for C168 admin use).",
    priceDescriptionDual:
      "Set default amounts for the company and group respectively. Company prices apply to company settings; group prices apply to group settings.",
    displayPrices: "Display prices",
    editPeriodHint: "Enter amounts for each period (up to 2 decimal places).",
    editFieldHint: "Edit fields below support up to 2 decimal places.",
    editWord: "edit",
    pricePlaceholder: "0.00",
    confirmDeleteTitle: "Confirm Delete",
    companyExpirationStatus: "Company Expiration Status",
    groupExpirationStatus: "Group Expiration Status",
    viewMoreCompaniesHint: "Click to view all companies and expiration dates",
    viewMoreGroupsHint: "Click to view all groups and expiration dates",
    noCompaniesFound: "No companies found",
    noGroupsFound: "No groups found",
    noExpirationDate: "No expiration date",
    noDateSet: "No date set",
    valid: "Valid",
    expirationPrefix: "Expiration: ",
  },
  zh: {
    pleaseEnterCompanyId: "请输入公司 ID",
    companyIdAlreadyAdded: "该公司 ID 已添加",
    cannotAddGroupUsesCompanyId:
      "「{id}」已是公司 ID，不能作为集团 ID。请换一个集团编码。",
    cannotAddCompanyUsesGroupId:
      "「{id}」已是集团 ID，不能作为公司 ID。请换一个公司编码，或先修改/删除该集团。",
    groupCompanyIdOverlapSave:
      "无法保存：「{id}」同时作为集团 ID 与公司 ID，请只保留其一或更名。",
    pleaseEnterGroupId: "请输入 Group ID",
    groupIdAlreadyExists: "Group ID 已存在",
    groupAdded: '集团 "{gid}" 已添加！',
    confirmDeleteGroupWithCount: '确定删除集团 "{gid}" 吗？\n\n此集团内 {count} 家公司将被取消集团。',
    confirmDeleteGroup: '确定删除集团 "{gid}" 吗？',
    confirmDeleteCompany:
      '从该 Domain 移除公司 "{cid}" 吗？\n\n若已有账户或 Transaction Payment 数据，将仅解除 Domain 关联，账务数据全部保留。\n从未使用的空公司会被永久删除。',
    companyRemovedFromForm: '已从表单移除公司 "{cid}"，确认后将解除关联（保留账务）或删除空公司。',
    cannotRemoveC168Company: "不能移除公司 C168。",
    groupRemoved: '集团 "{gid}" 已删除',
    pleaseSelectGroupFirst: "请先选择集团",
    invalidEmailFormat: "请输入有效的邮箱地址",
    ownerUpdated: "拥有者更新成功！",
    ownerCreated: "拥有者创建成功！",
    operationFailed: "操作失败",
    validateDomainCodeUnavailable: "无法向服务器校验该编码是否可用，请检查网络后重试。",
    saveOwnerError: "保存拥有者时发生错误",
    noUngroupedCompaniesAvailable: "暂无未集团公司",  
    noCompaniesInGroup: '集团 "{gid}" 中没有公司，点击“多选分配”进行分配。',
    noUngroupedCompanies: "暂无未集团公司",
    notSet: "未设置",
    setExpirationDate: "设置到期日",
    set: "设置",
    remove: "移除",
    editDomain: "编辑域名",
    addDomain: "新增域名",
    domainInformation: "域名信息",
    companyInformation: "公司信息",
    ownerCode: "拥有者代码",
    name: "名称",
    email: "邮箱",
    password: "密码",
    showPassword: "显示密码",
    hidePassword: "隐藏密码",
    secondaryPassword: "二级密码",
    leaveEmptyKeepCurrentPassword: "留空则保持当前密码",
    sixDigitsOnly: "仅限6位数字",
    secondaryPwdRequirement: "必须为 6 位数字（0-9）",
    groupIdPlaceholder: "集团ID",
    add: "添加",
    companyIdPlaceholder: "公司ID",
    groupIdLabel: "集团 ID",
    companyIdLabel: "公司 ID",
    companyPanelAddHeading: "添加集团 / 公司",
    groupsSectionLabel: "集团",
    selectedCompaniesHint: "先点上方的集团标签可筛选列表；选好集团后可点「多选分配」批量勾选公司归入该集团。",
    groupLabel: "集团：",
    noGroupsCreated: "尚未创建集团",
    selectedGroups: "已选集团：",
    noGroupsAddedYet: "尚未添加集团",
    groupSettings: "集团设置",
    groupSettingsLower: "集团设置",
    groupPrefix: "集团：",
    groupUpdatedShareAfterSave: "集团设置已更新。保存域名后将应用分成比例。",
    groupUpdatedSuccess: "集团设置更新成功！",
    selectedCompanies: "已选公司：",
    done: "完成 ✓",
    doneCompact: "完成",
    multipleChoice: "多选分配",
    searchCompanyPlaceholder: "搜索公司…",
    selectAll: "全选",
    noCompaniesAddedYet: "尚未添加公司",
    confirm: "确认",
    cancel: "取消",
    failedToLoadDomainData: "加载域名数据失败",
    feeSummary: "显示：价格 {price}",
    groupPrice: "集团价格",
    companyPrice: "公司价格",
    feeInlineSummary: "集团 {group} · 公司 {company}",
    feeChipCompanyAria: "公司 Domain 价格（6 个月与 1 年）",
    feeChipGroupAria: "集团 Domain 价格（6 个月与 1 年）",
    selectOwnersToDeleteFirst: "请先选择要删除的拥有者",
    cannotDeleteC168Owners: "无法删除关联 C168 公司的拥有者",
    c168OwnersCannotDeleteOthersWillDelete: "关联 C168 公司的拥有者无法删除。其余 {count} 位拥有者将被删除。",
    confirmDeleteOwners: "确定要删除以下 {count} 位拥有者吗？\n\n{names}",
    deletedOwnersSuccess: "成功删除 {ok} 位拥有者！",
    deletionCompleted: "删除完成：成功 {ok}，失败 {fail}",
    batchDeleteError: "批量删除时发生错误",
    domainList: "域名列表",
    addDomainBtn: "新增域名",
    searchPlaceholder: "按拥有者名称/公司搜索",
    price: "价格",
    deleteWithCount: "删除（{count}）",
    delete: "删除",
    no: "序号:",
    ownerCodeWithColon: "拥有者代码:",
    nameWithColon: "名称:",
    emailWithColon: "邮箱:",
    companiesWithColon: "公司:",
    createdBy: "创建者:",
    action: "操作:",
    edit: "编辑",
    selectOwnerForDelete: "选择要删除的拥有者",
    paginationOf: "{page} / {total}",
    loadAccountFormFailed: "加载账号表单数据失败。",
    pleaseEnterCurrencyCode: "请输入币种代码",
    currencyExists: "币种 {code} 已存在",
    createCurrencyFailed: "创建币种失败",
    currencyCreatedSuccess: "币种 {code} 创建成功",
    confirmDeleteCurrency: "确定永久删除币种 {code} 吗？此操作不可撤销。",
    deleteCurrencyFailed: "删除币种失败",
    deleteCurrencySuccess: "币种 {code} 删除成功！",
    addAccountFailed: "新增账号失败",
    addAccountSuccess: "账号新增成功。",
    addAccountTitle: "新增账号",
    personalInformation: "个人信息",
    accountId: "账号 ID",
    role: "角色",
    selectRole: "选择角色",
    payment: "支付",
    paymentAlert: "支付提醒",
    yes: "是",
    noWord: "否",
    alertType: "提醒类型",
    selectType: "选择类型",
    weekly: "每周",
    monthly: "每月",
    days: "{n} 天",
    startDate: "开始日期",
    pickDate: "选择日期",
    clearDate: "清除",
    alertAmount: "提醒金额",
    enterAmount: "输入金额",
    remark: "备注",
    advancedAccount: "高级账号",
    otherCurrency: "其他币种：",
    newCurrencyPlaceholder: "输入新币种代码（例如 USD）",
    createCurrency: "创建币种",
    noCurrenciesAvailable: "暂无可用币种。",
    deleteCurrencyPermanently: "永久删除币种",
    companyLabel: "公司：",
    addAccountBtn: "新增账号",
    companySettings: "公司设置",
    companySettingsLower: "公司设置",
    companyPrefix: "Company: ",
    renameIdLabel: "重命名 ID",
    renameIdPlaceholder: "输入新 ID",
    cannotRenameToC168: "不能重命名为 C168",
    cannotRenameC168: "C168 不能重命名",
    cannotModifyStartDateWhenExtending: "延长期限时无法修改开始日期",
    selectStartDateHint: "选择用于计算到期日的开始日期",
    period: "周期",
    selectPeriod: "选择周期",
    sevenDays: "7天",
    oneMonth: "1个月",
    threeMonths: "3个月",
    sixMonths: "6个月",
    oneYear: "1年",
    expirationDate: "到期日期",
    permissionsLabel: "权限（流程列表与数据采集）",
    permissionsHintLine: "选择该公司在「流程列表」与「数据采集」页面可访问的选项。",
    share: "分成比例 %",
    on: "开",
    off: "关",
    account: "账号",
    total: "金额",
    oneAccount: "1 个账号",
    accountCount: "{count} 个账号",
    shareTotal: "分成总计",
    manage: "管理",
    addNewAccount: "新增账号",
    removeRow: "移除此行",
    addAccountInline: "+ 添加账号",
    noLinkedAccounts: "暂无关联账号。",
    save: "保存",
    saving: "保存中...",
    reset: "重置",
    pleaseSelectOneCategory: "请至少选择一个类别",
    onlyOneCategoryAtTime: "一次只能选择一个类别",
    permissionsSaveFailed: "权限保存失败",
    companyUpdatedShareAfterSave: "公司设置已更新。保存域名后将应用分成比例。",
    shareSaveFailed: "分成比例保存失败",
    feePostsHint: " 在主弹窗点击“确认域名”后会记账。",
    companyShareChargeAria: "域名确认时计费",
    companyUpdatedSuccess: "公司设置更新成功！",
    commissionSettings: "佣金设置",
    commissionSettingsSaved: "佣金设置已保存。",
    serverUnreachableChangesKept: "无法连接服务器。更改已保留在本地，请重试。",
    couldNotLoadSettings: "无法加载设置",
    saved: "已保存",
    saveFailed: "保存失败",
    priceDescription: "为各周期设置默认金额（供 C168 管理员使用）。",
    priceDescriptionDual:
      "分别为公司与集团设置默认金额。公司价格用于公司设置；集团价格用于集团设置。",
    displayPrices: "展示价格",
    editPeriodHint: "在下方为各周期输入金额（最多 2 位小数）。",
    editFieldHint: "下方编辑字段最多支持 2 位小数。",
    editWord: "编辑",
    pricePlaceholder: "请输入价格",
    confirmDeleteTitle: "确认删除",
    companyExpirationStatus: "公司到期状态",
    groupExpirationStatus: "集团到期状态",
    viewMoreCompaniesHint: "点击查看全部公司及到期时间",
    viewMoreGroupsHint: "点击查看全部集团及到期时间",
    noCompaniesFound: "未找到公司",
    noGroupsFound: "未找到集团",
    noExpirationDate: "未设置到期日",
    noDateSet: "未设置日期",
    valid: "有效",
    expirationPrefix: "到期：",
  },
};

export const getDomainText = createGetText(DOMAIN_I18N);
