import { createGetText, toLocale } from "../shared/i18nHelpers.js";

export const MAINTENANCE_I18N = {
  en: {
    category: "Category:",
    groupId: "Group ID:",
    company: "Company:",
    currency: "Currency:",
    currencyAll: "All",
    process: "Process",
    dateRange: "Date Range",
    quickSelect: "Quick Select",
    period: "Period",
    selectDateRange: "Select date range",
    selectEndDate: "Select end date",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",
    delete: "Delete",
    confirmDelete: "Confirm Delete",
    confirmDeleteTitle: "Confirm Delete",
    cancel: "Cancel",
    loading: "Loading...",
    selectAll: "Select All",
    alreadyDeleted: "Already deleted",
    noDataAdjustSearch: "No data found. Please adjust your search criteria and try again.",
    noBankProcessAdjustSearch:
      "No bank process transactions found. Please adjust your search criteria and try again.",
    selectAllProcesses: "Select All",
    selectProcessPrompt: "Select process",
    searchProcessPlaceholder: "Search process...",
    noResultsFound: "No results found",
    switchedTo: "Switched to {company}",
    switchFailed: "Switch failed",
    failedLoadProcesses: "Failed to load processes",
    failedLoadMetaData: "Failed to load meta data",
    failedLoadCompanyMetadata: "Failed to load company metadata",
    foundRecords: "Found {n} record(s)",
    pleaseSelectOneRecord: "Please select at least one record",
    deleteSuccessful: "Delete successful",
    pleaseConfirmDeleteCheckbox: "Please check the confirm delete checkbox",
    pleaseConfirmDeletionCheckbox: "Please confirm deletion by checking the checkbox",
    deleteConfirmRecords:
      "Are you sure you want to delete the selected {count} record(s)? This action cannot be undone.",
    deleteConfirmBankProcess:
      "Are you sure you want to delete the selected {count} bank process transaction(s)? This action cannot be undone.",
    operationCompletedSuccess: "Operation completed successfully!",
    operationFailedRetry: "Operation failed. Please try again.",
    noDataFound: "No data found",
    successfullyDeletedN: "Successfully deleted {n} record(s)",
    successfullyDeletedBankProcessN: "Successfully deleted {n} bank process transaction record(s)",
    deleteFailed: "Delete failed",
    updateSuccessful: "Update successful",
    saveFailed: "Save failed",
    pleaseSelectDateRange: "Please select date range",
    noBankProcessTransactions: "No bank process transactions found",
    searchFailed: "Search failed",
    searchRetrying: "Loading data…",
    searchRetryHint: "Loading is taking longer. Try a shorter date range or select a Process.",
    searchNetworkError:
      "Network connection interrupted. Please retry or use a shorter date range.",
    searchRangeTooLarge:
      "This date range returns too much data. Narrow the dates or select a Process, then try again.",

    pageTitleDataCapture: "Maintenance - Data Capture",
    pageTitleFormula: "Maintenance - Formula",
    pageTitlePayment: "Maintenance - Payment",
    pageTitleTransaction: "Maintenance - Transaction",
    pageTitleBankProcess: "Maintenance - {category}",
    bankProcessCategoryFallback: "Process",

    maintenancePrefix: "Maintenance",
    titleDataCapture: "Data Capture",
    titleFormula: "Formula",
    titlePayment: "Payment",
    titleTransaction: "Transaction",

    tblNo: "No.",
    tblDtsCreated: "Dts Created",
    tblProduct: "Product",
    tblProcess: "Process",
    tblCurrency: "Currency",
    tblWlGroup: "W/L Group",
    tblSubmittedBy: "Submitted By",
    tblDeletedBy: "Deleted By",
    tblCreatedAt: "Created At",
    tblAccountTo: "Account(To)",
    tblAccountFrom: "Account(From)",
    tblAmount: "Amount",
    tblDescription: "Description",
    tblRemark: "Remark",
    tblSubmitter: "Submitter",
    tblDeleter: "Deleter",
    tblAccount: "Account",
    tblFrom: "From",
    tblIdProduct: "Id_Product",
    tblPercent: "Percent",
    tblRate: "Rate",
    tblCr: "Cr",
    tblDr: "Dr",
    tblSource: "Source",
    tblInputMethod: "Input Method",
    tblFormula: "Formula",

    transactionType: "Transaction Type",
    allTypes: "All Types",
    search: "Search",
    searchFormulaPlaceholder: "Search process, account, product...",
    clearFiltersTitle: "Clear Filters",
    selectAccount: "Select Account",

    bankSearchPlaceholder: "e.g. TEST M16(CIMB) / CIMB",

    edit: "Edit",
    save: "Save",

    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
  zh: {
    category: "类别：",
    groupId: "集团：",
    company: "公司：",
    currency: "货币：",
    currencyAll: "All",
    process: "流程",
    dateRange: "日期范围",
    quickSelect: "快捷选择",
    period: "周期",
    selectDateRange: "选择日期范围",
    selectEndDate: "选择结束日期",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    lastYear: "去年",
    delete: "删除",
    confirmDelete: "确认删除",
    confirmDeleteTitle: "确认删除",
    cancel: "取消",
    loading: "加载中...",
    selectAll: "全选",
    alreadyDeleted: "已删除",
    noDataAdjustSearch: "暂无数据。请调整筛选条件后重试。",
    noBankProcessAdjustSearch: "未找到银行流程交易记录。请调整筛选条件后重试。",
    selectAllProcesses: "全部",
    selectProcessPrompt: "请选择流程",
    searchProcessPlaceholder: "搜索流程...",
    noResultsFound: "无匹配结果",
    switchedTo: "已切换到 {company}",
    switchFailed: "切换失败",
    failedLoadProcesses: "加载流程失败",
    failedLoadMetaData: "加载元数据失败",
    failedLoadCompanyMetadata: "加载公司信息失败",
    foundRecords: "共找到 {n} 条记录",
    pleaseSelectOneRecord: "请至少选择一条记录",
    deleteSuccessful: "删除成功",
    pleaseConfirmDeleteCheckbox: "请先勾选确认删除",
    pleaseConfirmDeletionCheckbox: "请先勾选确认删除",
    deleteConfirmRecords: "确定要删除已选中的 {count} 条记录吗？此操作不可撤销。",
    deleteConfirmBankProcess: "确定要删除已选中的 {count} 笔银行流程交易吗？此操作不可撤销。",
    operationCompletedSuccess: "操作成功完成！",
    operationFailedRetry: "操作失败，请重试。",
    noDataFound: "暂无数据",
    successfullyDeletedN: "已成功删除 {n} 条记录",
    successfullyDeletedBankProcessN: "已成功删除 {n} 笔银行流程交易记录",
    deleteFailed: "删除失败",
    updateSuccessful: "更新成功",
    saveFailed: "保存失败",
    pleaseSelectDateRange: "请选择日期范围",
    noBankProcessTransactions: "未找到银行流程交易",
    searchFailed: "搜索失败",
    searchRetrying: "正在加载数据…",
    searchRetryHint: "加载较慢，请缩小日期范围或选择 Process。",
    searchNetworkError: "网络连接中断，请重试或缩小日期范围。",
    searchRangeTooLarge: "该日期段数据量过大，请缩小日期范围或选择 Process 后再试。",

    pageTitleDataCapture: "维护 - 数据采集",
    pageTitleFormula: "维护 - 公式",
    pageTitlePayment: "维护 - 支付",
    pageTitleTransaction: "维护 - 交易",
    pageTitleBankProcess: "维护 - {category}",
    bankProcessCategoryFallback: "流程",

    maintenancePrefix: "维护",
    titleDataCapture: "数据采集",
    titleFormula: "公式",
    titlePayment: "支付",
    titleTransaction: "交易",

    tblNo: "序号",
    tblDtsCreated: "创建时间",
    tblProduct: "产品",
    tblProcess: "流程",
    tblCurrency: "币种",
    tblWlGroup: "输赢组",
    tblSubmittedBy: "提交人",
    tblDeletedBy: "删除人",
    tblCreatedAt: "创建时间",
    tblAccountTo: "账户（入）",
    tblAccountFrom: "账户（出）",
    tblAmount: "金额",
    tblDescription: "说明",
    tblRemark: "备注",
    tblSubmitter: "提交人",
    tblDeleter: "删除人",
    tblAccount: "账户",
    tblFrom: "来源",
    tblIdProduct: "产品编号",
    tblPercent: "百分比",
    tblRate: "汇率",
    tblCr: "贷",
    tblDr: "借",
    tblSource: "来源列",
    tblInputMethod: "输入方式",
    tblFormula: "公式",

    transactionType: "交易类型",
    allTypes: "全部类型",
    search: "搜索",
    searchFormulaPlaceholder: "搜索流程、账户、产品...",
    clearFiltersTitle: "清除筛选",
    selectAccount: "选择账户",

    bankSearchPlaceholder: "例如 TEST M16(CIMB) / CIMB",

    edit: "编辑",
    save: "保存",

    monthsShort: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    weekdaysShort: ["日", "一", "二", "三", "四", "五", "六"],
  },
};

const INPUT_METHOD_META = [
  { value: "", key: "inputMethodPlaceholder" },
  { value: "positive_to_negative_negative_to_positive", key: "inputMethodPnNp" },
  { value: "positive_to_negative_negative_to_zero", key: "inputMethodPnNz" },
  { value: "negative_to_positive_positive_to_zero", key: "inputMethodNpPz" },
  { value: "positive_unchanged_negative_to_zero", key: "inputMethodPuNz" },
  { value: "negative_unchanged_positive_to_zero", key: "inputMethodNuPz" },
  { value: "change_to_positive", key: "inputMethodToPositive" },
  { value: "change_to_negative", key: "inputMethodToNegative" },
  { value: "change_to_zero", key: "inputMethodToZero" },
];

const INPUT_METHOD_LABEL_KEYS = {
  en: {
    inputMethodPlaceholder: "Select Input Method (Optional)",
    inputMethodPnNp: "Positive to negative, negative to positive",
    inputMethodPnNz: "Positive to negative, negative to zero",
    inputMethodNpPz: "Negative to positive, positive to zero",
    inputMethodPuNz: "Positive unchanged, negative to zero",
    inputMethodNuPz: "Negative unchanged, positive to zero",
    inputMethodToPositive: "Change to positive",
    inputMethodToNegative: "Change to negative",
    inputMethodToZero: "Change to zero",
  },
  zh: {
    inputMethodPlaceholder: "选择输入方式（可选）",
    inputMethodPnNp: "正转负，负转正",
    inputMethodPnNz: "正转负，负转零",
    inputMethodNpPz: "负转正，正转零",
    inputMethodPuNz: "正不变，负转零",
    inputMethodNuPz: "负不变，正转零",
    inputMethodToPositive: "改为正",
    inputMethodToNegative: "改为负",
    inputMethodToZero: "改为零",
  },
};

export const getMaintenanceText = createGetText(MAINTENANCE_I18N);

export function getFormulaInputMethodOptions(lang) {
  const locale = toLocale(lang);
  const labels = INPUT_METHOD_LABEL_KEYS[locale];
  return INPUT_METHOD_META.map(({ value, key }) => ({
    value,
    text: labels[key] ?? INPUT_METHOD_LABEL_KEYS.en[key],
  }));
}
