import { createGetText } from "../shared/i18nHelpers.js";

export const OWNERSHIP_I18N = {
  en: {
    accountOwnership: "Account Ownership",
    groupEarnings: "Group Earnings",
    group: "Group",
    cancel: "Cancel",
    select: "Select",
    noCompaniesFound: "No companies found.",
    noGroupsFound: "No groups found. Assign companies to groups in the Account Ownership tab first.",
    totalAllocation: "Total Allocation",
    remaining: "Remaining",
    overLimit: "Over limit!",
    ungroup: "Ungroup",
    manage: "Manage",
    account: "Account",
    ownershipPercent: "Ownership%",
    addAccount: "+ Add Account",
    readOnly: "Read Only",
    remove: "Remove",
    confirm: "Confirm",
    saving: "Saving...",
    fullyAllocated: "Fully Allocated",
    unallocated: "{value} Unallocated",
    overAllocated: "{value} Over Allocated",
    totalExceeds100: "Total exceeds 100%!",
    totalLessThan100: "Total is less than 100%",
    externalPartner: "External Partner",
    loginOrGroupId: "Login ID/Group ID",
    linking: "Linking...",
    linkPartner: "Link Partner",
    partnerDescCompany: "Share this company's read-only dashboard visibility with another independent owner.",
    partnerDescGroup: "Share this group's read-only dashboard visibility with another independent owner.",
    selectAccountPlaceholder: "-- SELECT ACCOUNT --",
    mainOwnerSuffix: " - Main",
    joinGroup: "+ Group",
    selected: "selected",
    selectGroupPlaceholder: "-- Select Group --",
    joinGroupAction: "Join Group",
    bulkCancel: "✕ Cancel",
    removedFromGroup: "\"{company}\" removed from group",
    joinedGroup: "\"{company}\" joined group \"{group}\"",
    pleaseSelectGroup: "Please select a group",
    addedCompaniesToGroup: "Added {count} companies to {group}",
    removedCompaniesFromGroup: "Removed {count} companies from group",
    succeededFailed: "{ok} succeeded, {failed} failed",
    failedToLoadCompanies: "Failed to load companies",
    failedToLoadGroups: "Failed to load groups",
    serverError: "Server error",
    errorLoadingData: "Error loading data",
    errorLoadingGroupData: "Error loading group data",
    readOnlyModifyBlocked: "Read-only: only owner can modify ownership",
    pleaseSelectAccountAllRows: "Please select an account for all rows.",
    pleaseSelectAccount: "Please select an account.",
    totalPercentageExceeds: "Total percentage exceeds 100%",
    duplicateAccountsDetected: "Duplicate accounts detected.",
    savedSuccessfully: "Saved successfully",
    saveFailed: "Save failed",
    groupSavedSuccessfully: "Group ownership saved successfully",
    partnerLinkedSuccessfully: "Partner linked successfully",
    linkPartnerFailed: "Link partner failed",
    joinGroupFailed: "Join group failed",
    ungroupFailed: "Ungroup failed",
    multipleMatchesFound: "Multiple Matches Found",
    idUsedByTwoPartners: "This ID is used by two different partners. Which one do you want to link?",
    linkAsLoginId: "Link as Login ID:",
    joinAsGroup: "Join Group:",
    multipleMatchesHint: "Multiple matches found. Please specify login or group ID more precisely.",
    viewMonth: "View month",
    currentMonth: "Current",
    historicalView: "Historical",
    noSnapshotForMonth: "No ownership snapshot saved for {month}.",
    historicalSnapshotSaved: "{month} snapshot (saved {savedAt})",
    noSnapshotShort: "No snapshot this month",
    snapshotSavedShort: "Saved {savedAt}",
    historicalEditHint: "Adjust accounts and percentages, then confirm to save this month.",
  },
  zh: {
    accountOwnership: "账号归属",
    groupEarnings: "分组收益",
    group: "分组",
    cancel: "取消",
    select: "选择",
    noCompaniesFound: "未找到公司。",
    noGroupsFound: "未找到分组。请先在账号归属页为公司分组。",
    totalAllocation: "总分配",
    remaining: "剩余",
    overLimit: "超出上限！",
    ungroup: "取消分组",
    manage: "管理",
    account: "账号",
    ownershipPercent: "归属比例%",
    addAccount: "+ 添加账号",
    readOnly: "只读",
    remove: "移除",
    confirm: "确认",
    saving: "保存中...",
    fullyAllocated: "已完全分配",
    unallocated: "{value} 未分配",
    overAllocated: "{value} 超额分配",
    totalExceeds100: "总比例超过 100%！",
    totalLessThan100: "总比例小于 100%",
    externalPartner: "外部伙伴",
    loginOrGroupId: "登录ID/分组ID",
    linking: "关联中...",
    linkPartner: "关联伙伴",
    partnerDescCompany: "将本公司看板以“仅查看（不可编辑）”权限共享给另一位独立所有者。",
    partnerDescGroup: "将本分组看板以“仅查看（不可编辑）”权限共享给另一位独立所有者。",
    selectAccountPlaceholder: "-- 选择账号 --",
    mainOwnerSuffix: " - 主账号",
    joinGroup: "+ 分组",
    selected: "已选",
    selectGroupPlaceholder: "-- 选择分组 --",
    joinGroupAction: "加入分组",
    bulkCancel: "✕ 取消",
    removedFromGroup: "\"{company}\" 已移出分组",
    joinedGroup: "\"{company}\" 已加入分组 \"{group}\"",
    pleaseSelectGroup: "请选择分组",
    addedCompaniesToGroup: "已将 {count} 个公司加入 {group}",
    removedCompaniesFromGroup: "已将 {count} 个公司移出分组",
    succeededFailed: "成功 {ok} 个，失败 {failed} 个",
    failedToLoadCompanies: "加载公司失败",
    failedToLoadGroups: "加载分组失败",
    serverError: "服务器错误",
    errorLoadingData: "加载数据失败",
    errorLoadingGroupData: "加载分组数据失败",
    readOnlyModifyBlocked: "只读模式：仅 owner 可修改归属",
    pleaseSelectAccountAllRows: "请为所有行选择账号。",
    pleaseSelectAccount: "请选择账号。",
    totalPercentageExceeds: "总比例超过 100%",
    duplicateAccountsDetected: "检测到重复账号。",
    savedSuccessfully: "保存成功",
    saveFailed: "保存失败",
    groupSavedSuccessfully: "分组归属保存成功",
    partnerLinkedSuccessfully: "伙伴关联成功",
    linkPartnerFailed: "关联伙伴失败",
    joinGroupFailed: "加入分组失败",
    ungroupFailed: "取消分组失败",
    multipleMatchesFound: "发现多个匹配",
    idUsedByTwoPartners: "该 ID 对应两个不同伙伴，你想关联哪一个？",
    linkAsLoginId: "按登录ID关联：",
    joinAsGroup: "加入分组：",
    multipleMatchesHint: "发现多个匹配，请更精确输入登录ID或分组ID。",
    viewMonth: "查看月份",
    currentMonth: "当前月",
    historicalView: "历史记录",
    noSnapshotForMonth: "{month} 暂无归属比例存档。",
    historicalSnapshotSaved: "{month} 存档（保存于 {savedAt}）",
    noSnapshotShort: "该月无存档",
    snapshotSavedShort: "保存于 {savedAt}",
    historicalEditHint: "可调整账户与比例，确认后保存至该月。",
  },
};

export const getOwnershipText = createGetText(OWNERSHIP_I18N);
