import { createGetText } from "../shared/i18nHelpers.js";

export const PROCESS_LIST_I18N = {
  en: {
    pageTitle: "Process List",
    addProcess: "Add Process",
    saving: "Saving...",
    search: "Search",
    showAll: "Show All",
    showInactive: "Show Inactive",
    delete: "Delete",
    deleteWithCount: "Delete ({count})",
    groupId: "Group ID:",
    groupFilterAll: "ALL",
    currency: "Currency:",
    currencyDragHint: "Drag to reorder · Click to filter",
    company: "Company:",
    loadingData: "Load the Data...",
    failedLoadProcessList: "Failed to load process list",
    descExists: "Description name already exists",
    failedAddDescription: "Failed to add description",
    descAdded: "Description added successfully!",
    failedDeleteDescription: "Failed to delete description",
    descDeleted: "Description deleted",
    switchCompanyFailed: "Switch company failed",
    failedLoadProcess: "Failed to load process",
    currencyWarningNoCompany: "Warning: The original currency does not belong to your company. Please select a currency manually.",
    currencyWarningWithCode: "Warning: The original currency ({code}) does not belong to your company. Please select a currency manually.",
    needAtLeastOneDescription: "Please select at least one description",
    needProcessIdOrMulti: "Please enter Process ID or enable Multi-use Purpose",
    needOneMultiProcess: "Please select at least one process for Multi-use Purpose",
    updateFailed: "Update failed",
    processUpdated: "Process updated successfully!",
    createFailed: "Create failed",
    processAdded: "Process added successfully!",
    copyNoTemplates: "No templates found to copy",
    copySyncEnabled: "Sync enabled: changes will sync to these processes",
    copySyncNotSet: "Sync not set: source process not found for this company",
    processSkippedConflicts: "{count} process(es) were skipped due to conflicts.",
    deleteFailed: "Delete failed",
    processDeletedOne: "1 process deleted successfully",
    processDeletedMany: "{count} processes deleted successfully",
    statusUpdateFailed: "Status update failed",
    activated: "activated",
    deactivated: "deactivated",
    statusChangedTo: "Process status changed to {status}",
    pageOf: "{current} of {total}",
    processId: "Process ID",
    noColumn: "No",
    description: "Description",
    status: "Status",
    statusActive: "ACTIVE",
    statusInactive: "INACTIVE",
    statusWaiting: "WAITING",
    currencyColumn: "Currency",
    dayUse: "Day Use",
    action: "Action",
    selectAll: "Select all",
    selectAllInactiveOnPage: "Select all inactive processes on this page",
    noProcessData: "No process data found",
    clickToggleStatus: "Click to toggle status",
    edit: "Edit",
    selectForDeletion: "Select for deletion",
    confirmDeleteTitle: "Confirm Delete",
    confirmDeleteMessage: "Are you sure you want to delete {count} process(es)? This action cannot be undone.",
    cancel: "Cancel",
    deleting: "Deleting...",
    selectOrAddDescription: "Select or Add Description",
    selectedDescriptions: "Selected Descriptions",
    noDescriptionsSelected: "No descriptions selected",
    addNewDescription: "Add New Description",
    enterNewDescriptionName: "Enter new description name...",
    add: "Add",
    availableDescriptions: "Available Descriptions",
    searchDescriptions: "Search descriptions...",
    deleteDescription: "Delete Description",
    confirmSelection: "Confirm Selection",
    deleteDescriptionTitle: "Delete description",
    deleteDescriptionConfirm: "Are you sure you want to delete this description?",
    descriptionsSelectedCount: "{count} description(s) selected",
    selectProcessToCopyFrom: "Select Process to Copy From",
    editProcess: "Edit Process",
    copyFrom: "Copy From",
    unknown: "Unknown",
    noDescription: "No Description",
    searchProcess: "Search process...",
    clear: "— Clear —",
    processNameRequired: "Process Name *",
    processIdRequired: "Process ID *",
    enterProcessId: "Enter Process ID",
    multiProcess: "Multi-Process",
    selectMultiUseProcesses: "Select Multi-use Processes",
    confirm: "Confirm",
    selectedMultiUseProcesses: "Selected Multi-use Processes",
    descriptionRequired: "Description *",
    clickToSelectDescriptions: "Click + to select descriptions",
    chooseDescription: "Choose description",
    selectCurrency: "Select Currency",
    dtsModified: "DTS Modified:",
    dtsCreated: "DTS Created:",
    removeWords: "Remove Word",
    enterWordsToRemove: "Enter words to remove",
    removeWordsHelp: "Press Enter to add a word chip; saved for this process for next time.",
    removeWordChipRemove: "Remove",
    allDay: "ALL DAY",
    replaceFrom: "Replace From",
    oldWord: "Old word",
    wordToBeReplaced: "(Word to be replaced)",
    replaceTo: "Replace To",
    newWord: "New word",
    replacementWord: "(Replacement word)",
    remarks: "Remarks",
    enterRemarks: "Enter remarks...",
    updateProcess: "Update Process",
    readOnlyActionBlocked: "Read-only account: this action is not allowed.",
    processFormSectionBasic: "Information",
    processFormSectionRecord: "Record",
    processFormSectionTextReplace: "Text & replacement",
    processFormSectionScheduleNotes: "Schedule",
    dayMonday: "MON",
    dayTuesday: "TUE",
    dayWednesday: "WED",
    dayThursday: "THU",
    dayFriday: "FRI",
    daySaturday: "SAT",
    daySunday: "SUN",
  },
  zh: {
    pageTitle: "流程列表",
    addProcess: "新增流程",
    saving: "保存中...",
    search: "搜索",
    showAll: "显示全部",
    showInactive: "显示停用",
    delete: "删除",
    deleteWithCount: "删除（{count}）",
    groupId: "集团：",
    groupFilterAll: "ALL",
    currency: "货币：",
    currencyDragHint: "拖动调整顺序 · 点击筛选",
    company: "公司：",
    loadingData: "加载数据中...",
    failedLoadProcessList: "加载流程列表失败",
    descExists: "描述名称已存在",
    failedAddDescription: "新增描述失败",
    descAdded: "描述新增成功！",
    failedDeleteDescription: "删除描述失败",
    descDeleted: "描述已删除",
    switchCompanyFailed: "切换公司失败",
    failedLoadProcess: "加载流程失败",
    currencyWarningNoCompany: "警告：原货币不属于当前公司，请手动重新选择货币。",
    currencyWarningWithCode: "警告：原货币（{code}）不属于当前公司，请手动重新选择货币。",
    needAtLeastOneDescription: "请至少选择一个描述",
    needProcessIdOrMulti: "请输入流程ID或启用多流程用途",
    needOneMultiProcess: "请至少选择一个多流程用途",
    updateFailed: "更新失败",
    processUpdated: "流程更新成功！",
    createFailed: "创建失败",
    processAdded: "流程新增成功！",
    copyNoTemplates: "未找到可复制的模板",
    copySyncEnabled: "已启用同步：变更会同步到这些流程",
    copySyncNotSet: "未设置同步：当前公司找不到源流程",
    processSkippedConflicts: "有 {count} 个流程因冲突被跳过。",
    deleteFailed: "删除失败",
    processDeletedOne: "已成功删除 1 个流程",
    processDeletedMany: "已成功删除 {count} 个流程",
    statusUpdateFailed: "状态更新失败",
    activated: "启用",
    deactivated: "停用",
    statusChangedTo: "流程状态已更改为：{status}",
    pageOf: "{current} / {total}",
    processId: "流程ID",
    noColumn: "序号",
    description: "描述",
    status: "状态",
    statusActive: "启用",
    statusInactive: "停用",
    statusWaiting: "等待",
    currencyColumn: "货币",
    dayUse: "使用日期",
    action: "操作",
    selectAll: "全选",
    selectAllInactiveOnPage: "选择本页所有停用流程",
    noProcessData: "未找到流程数据",
    clickToggleStatus: "点击切换状态",
    edit: "编辑",
    selectForDeletion: "选择以删除",
    confirmDeleteTitle: "确认删除",
    confirmDeleteMessage: "确定删除 {count} 个流程吗？此操作不可撤销。",
    cancel: "取消",
    deleting: "删除中...",
    selectOrAddDescription: "选择或新增描述",
    selectedDescriptions: "已选描述",
    noDescriptionsSelected: "尚未选择描述",
    addNewDescription: "新增描述",
    enterNewDescriptionName: "输入新的描述名称...",
    add: "新增",
    availableDescriptions: "可用描述",
    searchDescriptions: "搜索描述...",
    deleteDescription: "删除描述",
    confirmSelection: "确认选择",
    deleteDescriptionTitle: "删除描述",
    deleteDescriptionConfirm: "确定要删除这个描述吗？",
    descriptionsSelectedCount: "已选择 {count} 个描述",
    selectProcessToCopyFrom: "选择要复制来源的流程",
    editProcess: "编辑流程",
    copyFrom: "复制来源",
    unknown: "未知",
    noDescription: "无描述",
    searchProcess: "搜索流程...",
    clear: "— 清空 —",
    processNameRequired: "流程名称 *",
    processIdRequired: "流程ID *",
    enterProcessId: "输入流程ID",
    multiProcess: "多流程",
    selectMultiUseProcesses: "选择多流程用途",
    confirm: "确认",
    selectedMultiUseProcesses: "已选多流程用途",
    descriptionRequired: "描述 *",
    clickToSelectDescriptions: "点击 + 选择描述",
    chooseDescription: "选择描述",
    selectCurrency: "选择货币",
    dtsModified: "修改时间：",
    dtsCreated: "创建时间：",
    removeWords: "移除词",
    enterWordsToRemove: "输入要移除的词",
    removeWordsHelp: "输入词语后按 Enter 添加为标签；会保存在当前 Process，下次可继续使用。",
    removeWordChipRemove: "移除",
    allDay: "全天",
    replaceFrom: "替换来源",
    oldWord: "旧词",
    wordToBeReplaced: "（将被替换的词）",
    replaceTo: "替换为",
    newWord: "新词",
    replacementWord: "（替换后的词）",
    remarks: "备注",
    enterRemarks: "输入备注...",
    updateProcess: "更新流程",
    readOnlyActionBlocked: "只读账号，无法执行此操作。",
    processFormSectionBasic: "信息",
    processFormSectionRecord: "记录信息",
    processFormSectionTextReplace: "文本与替换",
    processFormSectionScheduleNotes: "周期与备注",
    dayMonday: "周一",
    dayTuesday: "周二",
    dayWednesday: "周三",
    dayThursday: "周四",
    dayFriday: "周五",
    daySaturday: "周六",
    daySunday: "周日",
  },
};

const PROCESS_DAY_NAME_KEYS = {
  MON: "dayMonday",
  TUE: "dayTuesday",
  WED: "dayWednesday",
  THU: "dayThursday",
  FRI: "dayFriday",
  SAT: "daySaturday",
  SUN: "daySunday",
  MONDAY: "dayMonday",
  TUESDAY: "dayTuesday",
  WEDNESDAY: "dayWednesday",
  THURSDAY: "dayThursday",
  FRIDAY: "dayFriday",
  SATURDAY: "daySaturday",
  SUNDAY: "daySunday",
};

/** Process list table: localized status badge */
export function formatProcessStatusDisplay(t, status) {
  const s = String(status || "").trim().toLowerCase();
  if (s === "active") return t("statusActive");
  if (s === "inactive") return t("statusInactive");
  if (s === "waiting") return t("statusWaiting");
  return String(status || "").toUpperCase();
}

/** Process list table: localized day-use column (MON,TUE → 周一,周二) */
export function formatProcessDayUseDisplay(t, dayUse) {
  const raw = String(dayUse || "").trim();
  if (!raw) return "";
  return raw
    .split(/[,，]+/)
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => {
      const key = PROCESS_DAY_NAME_KEYS[part.toUpperCase()];
      return key ? t(key) : part.toUpperCase();
    })
    .join(",");
}

export const getProcessListText = createGetText(PROCESS_LIST_I18N);
