import { createGetText } from "../shared/i18nHelpers.js";

export const REPORT_I18N = {
  en: {
    customerReportTitle: "Customer Report",
    domainReportTitle: "Domain Report",
    switchFailed: "Switch failed",

    account: "Account",
    allAccounts: "All Accounts",
    accountDisabledGroupScope: "Select a company to filter by account",
    searchAccount: "Search account...",
    noResultsFound: "No results found",

    dateRange: "Date Range",
    selectDateRange: "Select date range",
    selectEndDate: "Select end date",
    periodShortcutsAria: "Period shortcuts",

    quickSelect: "Quick Select",
    period: "Period",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",

    showAll: "Show All",
    groupId: "Group ID:",
    groupFilterAll: "ALL",
    company: "Company:",
    currency: "Currency:",
    all: "All",

    process: "Process",
    selectProcess: "Select Process",
    allProcess: "All Process",
    searchProcess: "Search process...",

    colAccount: "Account",
    colName: "Name",
    colGroupId: "Group ID",
    colCompanyId: "Company",
    colCurrency: "Currency",
    colWin: "Win",
    colLose: "Lose",
    colProcess: "Process",
    colTurnover: "Turnover",
    colWinLose: "Win/Lose",

    loading: "Loading...",
    updatingReport: "Updating…",
    noDataFound: "No data found",
    noDataAdjustSearch: "No data found. Please adjust your search criteria and try again.",
    loadReportFailed: "Failed to load report",

    currencyLine: "Currency: {code}",
    currencyDash: "Currency: -",
    totalColon: "Total:",
    total: "Total",
    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
  zh: {
    customerReportTitle: "客户报表",
    domainReportTitle: "域名报表",
    switchFailed: "切换失败",

    account: "账号",
    allAccounts: "全部账号",
    accountDisabledGroupScope: "请先选择公司以按账户筛选",
    searchAccount: "搜索账号...",
    noResultsFound: "无匹配结果",

    dateRange: "日期范围",
    selectDateRange: "选择日期范围",
    selectEndDate: "选择结束日期",
    periodShortcutsAria: "周期快捷",

    quickSelect: "快捷选择",
    period: "周期",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    lastYear: "去年",

    showAll: "显示全部",
    groupId: "集团:",
    groupFilterAll: "ALL",
    company: "公司:",
    currency: "货币:",
    all: "ALL",

    process: "流程",
    selectProcess: "选择流程",
    allProcess: "全部流程",
    searchProcess: "搜索流程...",

    colAccount: "账号",
    colName: "名称",
    colGroupId: "集团",
    colCompanyId: "公司",
    colCurrency: "货币",
    colWin: "赢",
    colLose: "输",
    colProcess: "流程",
    colTurnover: "流水",
    colWinLose: "输赢",

    loading: "加载中...",
    updatingReport: "更新中…",
    noDataFound: "暂无数据",
    noDataAdjustSearch: "暂无数据。请调整筛选条件后重试。",
    loadReportFailed: "报表加载失败",

    currencyLine: "货币：{code}",
    currencyDash: "货币：-",
    totalColon: "合计：",
    total: "合计",
    monthsShort: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    weekdaysShort: ["日", "一", "二", "三", "四", "五", "六"],
  },
};

export const getReportText = createGetText(REPORT_I18N);
