import { createGetText } from "../shared/i18nHelpers.js";

export const TRANSACTION_I18N = {
  en: {
    transactionList: "Transaction List",
    contraInbox: "Contra Inbox",
    refresh: "Refresh",
    loading: "Loading...",
    date: "Date",
    from: "From",
    to: "To",
    currency: "Currency",
    amount: "Amount",
    submittedBy: "Submitted By",
    description: "Description",
    action: "Action",
    approve: "Approve",
    reject: "Reject",
    close: "Close",
    contraInboxAwaitingApproval: "{count} item awaiting approval",
    contraInboxAwaitingApprovalPlural: "{count} items awaiting approval",
    contraInboxEmpty: "No pending contra transactions for the selected company.",
    contraInboxEmptyHint: "Inbox shows pending approvals from users below Manager. Owner/Manager submissions are auto-approved.",
    confirmRejectContra: "Are you sure you want to reject this Contra transaction? Data will be permanently deleted after rejection.",
    showName: "Show Name",
    showCaptureOnly: "Show Win/Loss Only",
    showPaymentOnly: "Show Payment Only",
    showZeroBalance: "Show all 0 balance",
    category: "Category",
    selectAllCategories: "--Select All--",
    captureDate: "Capture Date",
    groupId: "Group ID:",
    all: "ALL",
    groupFilterAll: "ALL",
    company: "Company:",
    type: "Type",
    placeholderDdMmYyyy: "dd/mm/yyyy",
    transactionDate: "Transaction date",
    account: "Account",
    toAccount: "To Account",
    fromAccount: "From Account",
    selectToAccount: "--Select To Account--",
    selectFromAccount: "--Select From Account--",
    reverse: "Reverse",
    reverseAccounts: "Reverse accounts",
    selectCurrency: "--Select Currency--",
    rateTransactionDate: "Rate transaction date",
    rateMultiplier: "Rate multiplier",
    middleMan: "Middle-Man",
    selectMiddleManAccount: "--Select Account--",
    descriptionField: "Description",
    remark: "Remark",
    confirmSubmit: "Confirm Submit",
    submitting: "Submitting...",
    submit: "Submit",
    search: "Search",
    loadingData: "Loading data",
    accountTable: "Account",
    nameTable: "Name",
    bfTable: "B/F",
    winLossTable: "Win/Loss",
    crDrTable: "Cr/Dr",
    balanceTable: "Balance",
    total: "Total",
    currencyLabel: "Currency:",
    loadingHistory: "Loading history…",
    paymentHistorySubtitle: "Complete transaction history and balance details",
    paymentHistoryShowingEntries: "Showing {count} entries",
    idProduct: "Id Product",
    rate: "Rate",
    createdBy: "Created by",
    idProductCompact: "Product",
    currencyCompact: "CCY",
    winLossTableCompact: "W/L",
    balanceTableCompact: "Bal.",
    descriptionCompact: "Desc.",
    createdByCompact: "By",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",
    toleranceBanner: "Summary Win/Loss tolerance is enabled (<code>tx_wl_tol=1</code>): when absolute total Win/Loss ≤ <strong>RM1.00</strong>, <strong>0.00</strong> will be displayed, and Balance will be recalculated for that row; account columns &amp; API remain accurate.",
    pleaseSelectDateRange: "Please select date range",
    pleaseSelectAtLeastOneCurrency: "Please select at least one Currency or select All",
    searchCompletedNoData: "Search completed but no data found. Please check date range, Currency filter, or confirm data has been submitted",
    searchReturnedRowsNoneMatch: "Search returned {totalAccounts} row(s), but none match current display filters (e.g. zero balance hidden when \"Show 0 balance\" is off, or \"Show Payment Only\" / \"Show Win/Loss Only\"). Enable \"Show 0 balance\" or adjust filters.",
    searchCompletedFoundRecords: "Search completed, found {displayed} record(s)",
    searchFailed: "Search failed",
    searchFailedWithMessage: "Search failed: {message}",
    couldNotResolveAccount: "Could not resolve account for this row",
    synced: "Synced {text}",
    syncedAmount: "Synced Amount: {amount}",
    syncedFromAccount: "From Account: {account}",
    syncedToAccount: "To Account: {account}",
    syncedAmountShort: "Amount: {amount}",
    syncedCurrency: "Currency: {currency}",
    fromAccount: "From",
    toAccount: "To",
    readOnlyModeCannotSubmit: "Read-only mode: cannot submit transactions",
    pleaseSelectTransactionType: "Please select transaction type",
    pleaseSelectToAccount: "Please select To Account",
    profitPleaseSelectFromAccount: "PROFIT: Please select From Account",
    profitSameAccountError: "PROFIT: Select To Account and Select From Account cannot be the same",
    paymentContraEtcNeedFromAccount: "PAYMENT/CONTRA/CLAIM/CLEAR transaction requires From Account",
    receiveTypeDisabled: "RECEIVE transaction type is no longer available",
    pleaseSelectTransactionDate: "Please select transaction date",
    rateTransactionNeedFromAccount: "Rate transaction requires From Account",
    pleaseSelectBothCurrencies: "Please select both currencies",
    pleaseEnterValidCurrencyAmounts: "Please enter valid currency amounts",
    pleaseEnterValidRateValue: "Please enter a valid rate value (supports * and /, max 8 decimal places)",
    pleaseSelectMiddleManAccount: "Please select Middle-Man account",
    pleaseEnterMiddleManRate: "Please enter Middle-Man rate multiplier",
    middleManRateMaxDecimals: "Middle-Man rate supports max 8 decimal places",
    submittedWaitingApproval: "Submitted. Waiting for Manager+ approval to take effect.",
    rateTransactionSubmitted: "RATE transaction submitted successfully",
    transactionSubmitted: "Transaction submitted successfully",
    submitFailed: "Submit failed",
    networkError: "Network error. Please try again.",
    pleaseEnterValidAmount: "Please enter a valid amount",
    pleaseEnterNonZeroAdjustment: "Please enter a non-zero adjustment amount",
    profitEnterNonZeroAmount: "PROFIT: enter a non-zero amount (positive = WIN, negative = LOSE)",
    pleaseEnterValidAmountGteZero: "Please enter a valid amount (>= 0)",
    pleaseSelectCurrency: "Please select Currency",
    monthsShort: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
  },
  zh: {
    transactionList: "交易列表",
    contraInbox: "抵消收件箱",
    refresh: "刷新",
    loading: "加载中...",
    date: "日期",
    from: "来自",
    to: "至",
    currency: "货币",
    amount: "金额",
    submittedBy: "提交人",
    description: "说明",
    action: "操作",
    approve: "批准",
    reject: "拒绝",
    close: "关闭",
    contraInboxAwaitingApproval: "{count} 条待审批",
    contraInboxAwaitingApprovalPlural: "{count} 条待审批",
    contraInboxEmpty: "当前所选公司暂无待审批的抵消交易。",
    contraInboxEmptyHint: "收件箱显示 Manager 以下用户提交的待审批交易；Owner/Manager 自己提交的交易会自动批准，不会出现在此处。",
    confirmRejectContra: "确定要拒绝这条抵消交易吗？拒绝后数据将被永久删除。",
    showName: "显示名称",
    showCaptureOnly: "仅显示输赢",
    showPaymentOnly: "仅显示支付",
    showZeroBalance: "显示所有0余额",
    category: "类别",
    selectAllCategories: "--全选--",
    captureDate: "捕获日期",
    groupId: "集团：",
    groupFilterAll: "全部",
    all: "ALL",
    company: "公司：",
    type: "类型",
    placeholderDdMmYyyy: "日/月/年",
    transactionDate: "交易日期",
    account: "账户",
    toAccount: "转入账户",
    fromAccount: "转出账户",
    selectToAccount: "--选择转入账户--",
    selectFromAccount: "--选择转出账户--",
    reverse: "互换",
    reverseAccounts: "互换账户",
    selectCurrency: "--选择货币--",
    rateTransactionDate: "汇率交易日期",
    rateMultiplier: "汇率乘数",
    middleMan: "中间人",
    selectMiddleManAccount: "--选择账户--",
    descriptionField: "说明",
    remark: "备注",
    confirmSubmit: "确认提交",
    submitting: "提交中...",
    submit: "提交",
    search: "搜索",
    loadingData: "正在加载数据",
    accountTable: "账户",
    nameTable: "名称",
    bfTable: "期初",
    winLossTable: "输赢",
    crDrTable: "借/贷",
    balanceTable: "余额",
    total: "合计",
    currencyLabel: "货币：",
    loadingHistory: "正在加载历史记录…",
    paymentHistorySubtitle: "完整交易历史与余额明细",
    paymentHistoryShowingEntries: "共 {count} 条记录",
    idProduct: "产品编号",
    rate: "汇率",
    createdBy: "创建者",
    idProductCompact: "产品",
    currencyCompact: "币种",
    winLossTableCompact: "输赢",
    balanceTableCompact: "余额",
    descriptionCompact: "说明",
    createdByCompact: "创建",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    lastYear: "去年",
    toleranceBanner: "已启用底部 Summary Win/Loss 展示容差（<code>tx_wl_tol=1</code>）：合计 Win/Loss 绝对值不超过 <strong>RM1.00</strong> 时将显示 <strong>0.00</strong>，并重算该行 Balance；各账户列与 API 仍为真实轧差。",
    pleaseSelectDateRange: "请选择日期范围",
    pleaseSelectAtLeastOneCurrency: "请至少选择一个货币或选择全部",
    searchCompletedNoData: "搜索完成但未找到数据。请检查日期范围、货币筛选，或确认数据已提交",
    searchReturnedRowsNoneMatch: "搜索返回 {totalAccounts} 条记录，但没有符合当前显示筛选条件的记录（例如：未开启「显示0余额」时隐藏了0余额，或开启了「仅显示支付」/「仅显示输赢」）。请开启「显示0余额」或调整筛选条件。",
    searchCompletedFoundRecords: "搜索完成，找到 {displayed} 条记录",
    searchFailed: "搜索失败",
    searchFailedWithMessage: "搜索失败: {message}",
    couldNotResolveAccount: "无法解析此记录的账户",
    synced: "已同步 {text}",
    syncedAmount: "已同步金额: {amount}",
    syncedFromAccount: "从账户: {account}",
    syncedToAccount: "到账户: {account}",
    syncedAmountShort: "金额: {amount}",
    syncedCurrency: "货币: {currency}",
    fromAccount: "从账户",
    toAccount: "到账户",
    readOnlyModeCannotSubmit: "只读模式：无法提交交易",
    pleaseSelectTransactionType: "请选择交易类型",
    pleaseSelectToAccount: "请选择到账户",
    profitPleaseSelectFromAccount: "利润：请选择从账户",
    profitSameAccountError: "利润：选择到账户和选择从账户不能相同",
    paymentContraEtcNeedFromAccount: "支付/抵消/索赔/清算交易需要从账户",
    receiveTypeDisabled: "RECEIVE 交易类型已停用",
    pleaseSelectTransactionDate: "请选择交易日期",
    rateTransactionNeedFromAccount: "汇率交易需要从账户",
    pleaseSelectBothCurrencies: "请选择两种货币",
    pleaseEnterValidCurrencyAmounts: "请输入有效的货币金额",
    pleaseEnterValidRateValue: "请输入有效的汇率值（支持 * 和 /，最多8位小数）",
    pleaseSelectMiddleManAccount: "请选择中间人账户",
    pleaseEnterMiddleManRate: "请输入中间人汇率乘数",
    middleManRateMaxDecimals: "中间人汇率最多支持8位小数",
    submittedWaitingApproval: "已提交。等待经理以上级别批准后生效。",
    rateTransactionSubmitted: "汇率交易提交成功",
    transactionSubmitted: "交易提交成功",
    submitFailed: "提交失败",
    networkError: "网络错误。请重试。",
    pleaseEnterValidAmount: "请输入有效的金额",
    pleaseEnterNonZeroAdjustment: "请输入非零的调整金额",
    profitEnterNonZeroAmount: "利润：输入非零金额（正数=赢，负数=输）",
    pleaseEnterValidAmountGteZero: "请输入有效的金额（>= 0）",
    pleaseSelectCurrency: "请选择货币",
    monthsShort: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    weekdaysShort: ["日", "一", "二", "三", "四", "五", "六"],
  },
};

export const getTransactionText = createGetText(TRANSACTION_I18N);
