import { createGetText, toLocale } from "../shared/i18nHelpers.js";

export const USER_LIST_I18N = {
  en: {
    failedToLoadUsers: "Failed to load users",
    couldNotSwitchCompany: "Could not switch company",
    companySwitchFailed: "Company switch failed",
    noPermissionCreateAccounts: "You do not have permission to create new accounts",
    onlyOwnerCanEditOwner: "Only the owner can edit owner records",
    loadUserFailed: "Load user failed",
    toggleFailed: "Toggle failed",
    statusUpdated: "Status updated",
    deletedUsersSuccess: "Successfully deleted {count} users!",
    deletionResult: "Deletion: {ok} succeeded, {fail} failed",
    passwordRequired: "Password is required",
    invalidEmailFormat: "Please enter a valid email address",
    secondaryPasswordMustBe6Digits: "Secondary password must be 6 digits",
    saveFailed: "Save failed",
    saved: "Saved",
    readOnlyActionBlocked: "Read-only account: this action is not allowed.",
    userList: "User List",
    addUser: "Add User",
    searchPlaceholder: "Search Login ID,Name,Email",
    showInactive: "Show Inactive",
    inactive: "Inactive",
    showAll: "Show All",
    deleteWithCount: "Delete ({count})",
    deleteConfirmWithCount: "Are you sure you want to delete the following {count} user(s)?",
    groupId: "Group ID:",
    groupFilterAll: "ALL",
    company: "Company:",
    no: "No",
    loginId: "Login ID",
    name: "Name",
    email: "Email",
    role: "Role",
    status: "Status",
    statusActive: "ACTIVE",
    statusInactive: "INACTIVE",
    rolePartnership: "Partnership",
    roleAdmin: "Admin",
    roleManager: "Manager",
    roleSupervisor: "Supervisor",
    roleAccountant: "Accountant",
    roleAudit: "Audit",
    roleCustomerService: "Customer Service",
    roleCompany: "Company",
    roleOwner: "Owner",
    lastLogin: "Last Login",
    createdBy: "Created By",
    action: "Action",
    selectAllDeletableAria: "Select all users that can be deleted",
    rowDeleteCheckboxAria: "Select user for deletion",
    loading: "Loading...",
    paginationOf: "{page} of {total}",
    editOwner: "Edit Owner",
    editUser: "Edit User",
    back: "Back",
    userInformation: "User Information",
    password: "Password",
    passwordRequiredMark: "Password *",
    secondaryPassword: "Secondary Password",
    secondaryPasswordPlaceholder: "Enter 6-digit password",
    nameRequired: "Name *",
    roleRequired: "Role *",
    selectRole: "Select Role",
    emailRequired: "Email *",
    companyRequired: "Company *",
    companyNoneSelected: "None selected",
    selectCompanies: "Choose companies",
    companySearchPlaceholder: "Filter by code…",
    companyPickerDone: "Done",
    companyPickerTitle: "Companies",
    groupRequired: "Group *",
    groupNoneSelected: "None selected",
    selectGroups: "Choose groups",
    groupSearchPlaceholder: "Filter by group…",
    groupPickerDone: "Done",
    groupPickerTitle: "Groups",
    groupCompanyRequired: "Group/Company *",
    groupCompanyNoneSelected: "None selected",
    selectGroupCompany: "Choose",
    groupCompanyPickerTitle: "Group / Company",
    groupsSectionTitle: "Groups",
    companiesSectionTitle: "Companies",
    groupCompanySelectionRequired: "Select at least one group or company",
    groupSelectionRequired: "Please select a group",
    permissions: "Permissions",
    selectPermissions: "Choose permissions",
    permissionsNoneSelected: "None selected",
    permissionsSelectedCount: "{count} selected",
    permissionPickerTitle: "Permissions",
    permissionPickerDone: "Done",
    permHome: "Home",
    permAdmin: "Admin",
    permOwnership: "Ownership",
    permReport: "Report",
    permMaintenance: "Maintenance",
    readOnly: "Read Only",
    dataCapture: "Data Capture",
    transactionPayment: "Transaction Payment",
    selectAll: "Select All",
    clearAll: "Clear All",
    account: "Account",
    process: "Process",
    save: "Save",
    saving: "Saving...",
    cancel: "Cancel",
    confirmDelete: "Confirm Delete",
    delete: "Delete",
    apiUserCreated: "User created successfully",
    apiOwnerUpdated: "Owner updated successfully",
    apiUserUpdated: "User updated successfully",
    apiUserUpdatedCompanyNote:
      "User updated successfully. Note: After removal, this user no longer belongs to the current company. Switch to another company they belong to if you need to continue.",
    apiUserDeleted: "User deleted successfully",
    apiUnauthorized: "Unauthorized access",
    apiInvalidRequest: "Invalid request",
    apiLoginIdExists: "Login ID already exists in the current company",
    apiEmailExists: "Email already exists in the current company",
    apiDuplicateEmail: "Duplicate email",
    apiDuplicateLoginId: "Duplicate login ID",
    apiDuplicateCompanyLink: "Duplicate company link for this user",
    apiDuplicateValue: "Duplicate value",
    apiDuplicateRecord: "Duplicate record",
    apiSaveCouldNotComplete: "Could not save changes. Please try again.",
    apiInvalidEmail: "Invalid email format",
    apiInvalidRole: "Invalid role",
    apiInvalidStatus: "Invalid status",
    apiCreateUserFailed: "Failed to create user",
    apiUpdateUserFailed: "Failed to update user",
    apiUserNotFound: "User not found",
    apiLoadUserFailed: "Failed to load user",
    apiCannotDeleteSelf: "You cannot delete your own account",
    apiOwnerCannotDelete: "Owner record cannot be deleted",
    apiOnlyOwnerCanDeleteOwner: "Only the owner can delete owner records",
    apiCannotDeleteSameRole: "You cannot delete accounts with the same role level",
    apiCannotDeleteHigherRole: "You cannot delete accounts with higher role level",
    apiCannotToggleSameRole: "You cannot toggle status of accounts with the same role level",
    apiCannotToggleHigherRole: "You cannot toggle status of accounts with higher role level",
    apiDeleteUserFailed: "Failed to delete user",
    apiCompanyUpdated: "Company updated",
    apiNoPermissionAccessCompany: "No permission to access this company",
    apiCompanyExpired: "Company has expired",
    apiMissingCompanyId: "Missing company_id parameter",
  },
  zh: {
    failedToLoadUsers: "加载用户失败",
    couldNotSwitchCompany: "无法切换公司",
    companySwitchFailed: "公司切换失败",
    noPermissionCreateAccounts: "您没有权限创建新账号",
    onlyOwnerCanEditOwner: "仅 Owner 可编辑 Owner 记录",
    loadUserFailed: "加载用户失败",
    toggleFailed: "切换状态失败",
    statusUpdated: "状态已更新",
    deletedUsersSuccess: "成功删除 {count} 位用户！",
    deletionResult: "删除结果：成功 {ok}，失败 {fail}",
    passwordRequired: "密码为必填项",
    invalidEmailFormat: "请输入有效的邮箱地址",
    secondaryPasswordMustBe6Digits: "二级密码必须为 6 位数字",
    saveFailed: "保存失败",
    saved: "保存成功",
    readOnlyActionBlocked: "只读账号，无法执行此操作。",
    userList: "用户列表",
    addUser: "新增用户",
    searchPlaceholder: "搜索 登入账号/姓名/邮箱",
    showInactive: "显示停用",
    inactive: "停用",
    showAll: "显示全部",
    deleteWithCount: "删除（{count}）",
    deleteConfirmWithCount: "确认删除以下 {count} 位用户吗？",
    groupId: "集团：",
    groupFilterAll: "全部",
    company: "公司：",
    no: "序号",
    loginId: "登录 ID",
    name: "姓名",
    email: "邮箱",
    role: "角色",
    status: "状态",
    statusActive: "启用",
    statusInactive: "停用",
    rolePartnership: "合伙",
    roleAdmin: "管理员",
    roleManager: "经理",
    roleSupervisor: "主管",
    roleAccountant: "会计",
    roleAudit: "审计",
    roleCustomerService: "客服",
    roleCompany: "公司",
    roleOwner: "所有者",
    lastLogin: "最后登录",
    createdBy: "创建者",
    action: "操作",
    selectAllDeletableAria: "全选可删除的用户",
    rowDeleteCheckboxAria: "选择该用户以加入删除",
    loading: "加载中...",
    paginationOf: "{page} / {total}",
    editOwner: "编辑 Owner",
    editUser: "编辑用户",
    back: "返回",
    userInformation: "用户信息",
    password: "密码",
    passwordRequiredMark: "密码 *",
    secondaryPassword: "二级密码",
    secondaryPasswordPlaceholder: "请输入 6 位密码",
    nameRequired: "姓名 *",
    roleRequired: "角色 *",
    selectRole: "选择角色",
    emailRequired: "邮箱 *",
    companyRequired: "公司 *",
    companyNoneSelected: "未选择",
    selectCompanies: "选择公司",
    companySearchPlaceholder: "按代码筛选…",
    companyPickerDone: "完成",
    companyPickerTitle: "公司",
    groupRequired: "集团 *",
    groupNoneSelected: "未选择",
    selectGroups: "选择集团",
    groupSearchPlaceholder: "按集团筛选…",
    groupPickerDone: "完成",
    groupPickerTitle: "集团",
    groupCompanyRequired: "集团/公司 *",
    groupCompanyNoneSelected: "未选择",
    selectGroupCompany: "选择",
    groupCompanyPickerTitle: "集团 / 公司",
    groupsSectionTitle: "集团",
    companiesSectionTitle: "公司",
    groupCompanySelectionRequired: "请至少选择一个集团或公司",
    groupSelectionRequired: "请选择集团",
    permissions: "权限",
    selectPermissions: "选择权限",
    permissionsNoneSelected: "未选择",
    permissionsSelectedCount: "已选 {count} 项",
    permissionPickerTitle: "权限",
    permissionPickerDone: "完成",
    permHome: "首页",
    permAdmin: "管理",
    permOwnership: "股权",
    permReport: "报表",
    permMaintenance: "维护",
    readOnly: "只读",
    dataCapture: "数据采集",
    transactionPayment: "交易付款",
    selectAll: "全选",
    clearAll: "清空",
    account: "账号",
    process: "流程",
    save: "保存",
    saving: "保存中...",
    cancel: "取消",
    confirmDelete: "确认删除",
    delete: "删除",
    apiUserCreated: "用户创建成功",
    apiOwnerUpdated: "Owner 更新成功",
    apiUserUpdated: "用户更新成功",
    apiUserUpdatedCompanyNote:
      "用户更新成功。注意：移除后用户将不再属于当前公司，如需继续操作请切换到用户所属的其他公司",
    apiUserDeleted: "用户删除成功",
    apiUnauthorized: "未授权访问",
    apiInvalidRequest: "无效请求",
    apiLoginIdExists: "当前公司中登录 ID 已存在",
    apiEmailExists: "当前公司中邮箱已存在",
    apiDuplicateEmail: "邮箱重复",
    apiDuplicateLoginId: "登录 ID 重复",
    apiDuplicateCompanyLink: "该用户与公司关联重复",
    apiDuplicateValue: "数据重复",
    apiDuplicateRecord: "记录重复",
    apiSaveCouldNotComplete: "无法保存，请稍后重试。",
    apiInvalidEmail: "邮箱格式无效",
    apiInvalidRole: "角色无效",
    apiInvalidStatus: "状态无效",
    apiCreateUserFailed: "创建用户失败",
    apiUpdateUserFailed: "更新用户失败",
    apiUserNotFound: "未找到用户",
    apiLoadUserFailed: "加载用户失败",
    apiCannotDeleteSelf: "不能删除自己的账号",
    apiOwnerCannotDelete: "Owner 记录不能删除，因为它是公司的所有者",
    apiOnlyOwnerCanDeleteOwner: "只有 owner 本人可以删除 owner 记录",
    apiCannotDeleteSameRole: "不能删除同级角色的账号",
    apiCannotDeleteHigherRole: "不能删除更高角色级别的账号",
    apiCannotToggleSameRole: "不能切换同级角色的账号状态",
    apiCannotToggleHigherRole: "不能切换更高角色级别的账号状态",
    apiDeleteUserFailed: "删除用户失败",
    apiCompanyUpdated: "公司已更新",
    apiNoPermissionAccessCompany: "无权限访问该公司",
    apiCompanyExpired: "公司已过期",
    apiMissingCompanyId: "缺少 company_id 参数",
  },
};

function normApiMessage(message) {
  return String(message || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, " ")
    .replace(/[.!?！。]+$/g, "");
}

const USER_LIST_API_MESSAGE_KEYS = {
  [normApiMessage("User created successfully")]: "apiUserCreated",
  [normApiMessage("Owner updated successfully")]: "apiOwnerUpdated",
  [normApiMessage("User updated successfully")]: "apiUserUpdated",
  [normApiMessage("User deleted successfully")]: "apiUserDeleted",
  [normApiMessage("Users retrieved successfully")]: "saved",
  [normApiMessage("Unauthorized access")]: "apiUnauthorized",
  [normApiMessage("Invalid request")]: "apiInvalidRequest",
  [normApiMessage("You do not have permission to create new accounts")]: "noPermissionCreateAccounts",
  [normApiMessage("只读账号无法执行此操作")]: "readOnlyActionBlocked",
  [normApiMessage("Read-only account: this action is not allowed.")]: "readOnlyActionBlocked",
  [normApiMessage("只有owner本人可以编辑owner记录")]: "onlyOwnerCanEditOwner",
  [normApiMessage("Only the owner can edit owner records")]: "onlyOwnerCanEditOwner",
  [normApiMessage("Login ID already exists in current company")]: "apiLoginIdExists",
  [normApiMessage("Login ID already exists in one of the selected companies")]: "apiLoginIdExists",
  [normApiMessage("Email already exists in current company")]: "apiEmailExists",
  [normApiMessage("Email already exists in one of the selected companies")]: "apiEmailExists",
  [normApiMessage("Duplicate email")]: "apiDuplicateEmail",
  [normApiMessage("Duplicate login ID")]: "apiDuplicateLoginId",
  [normApiMessage("Duplicate company link for this user")]: "apiDuplicateCompanyLink",
  [normApiMessage("Duplicate value")]: "apiDuplicateValue",
  [normApiMessage("Duplicate record")]: "apiDuplicateRecord",
  [normApiMessage("Could not save changes. Please try again.")]: "apiSaveCouldNotComplete",
  [normApiMessage("Invalid email format")]: "apiInvalidEmail",
  [normApiMessage("Invalid role")]: "apiInvalidRole",
  [normApiMessage("Invalid status")]: "apiInvalidStatus",
  [normApiMessage("Failed to create user")]: "apiCreateUserFailed",
  [normApiMessage("Failed to update user")]: "apiUpdateUserFailed",
  [normApiMessage("Failed to update owner")]: "apiUpdateUserFailed",
  [normApiMessage("User not found")]: "apiUserNotFound",
  [normApiMessage("User not found or access denied")]: "apiUserNotFound",
  [normApiMessage("Owner not found or access denied")]: "apiUserNotFound",
  [normApiMessage("Load user failed")]: "apiLoadUserFailed",
  [normApiMessage("You cannot delete your own account")]: "apiCannotDeleteSelf",
  [normApiMessage("Owner记录不能删除，因为它是公司的所有者")]: "apiOwnerCannotDelete",
  [normApiMessage("只有owner本人可以删除owner记录")]: "apiOnlyOwnerCanDeleteOwner",
  [normApiMessage("You cannot delete accounts with the same role level")]: "apiCannotDeleteSameRole",
  [normApiMessage("You cannot delete accounts with higher role level")]: "apiCannotDeleteHigherRole",
  [normApiMessage("You cannot toggle status of accounts with the same role level")]: "apiCannotToggleSameRole",
  [normApiMessage("You cannot toggle status of accounts with higher role level")]: "apiCannotToggleHigherRole",
  [normApiMessage("状态更新成功")]: "statusUpdated",
  [normApiMessage("Status updated")]: "statusUpdated",
  [normApiMessage("Toggle failed")]: "toggleFailed",
  [normApiMessage("切换状态失败")]: "toggleFailed",
  [normApiMessage("Company updated")]: "apiCompanyUpdated",
  [normApiMessage("Company 已更新")]: "apiCompanyUpdated",
  [normApiMessage("No permission to access this company")]: "apiNoPermissionAccessCompany",
  [normApiMessage("无权限访问该公司")]: "apiNoPermissionAccessCompany",
  [normApiMessage("Company has expired")]: "apiCompanyExpired",
  [normApiMessage("Missing company_id parameter")]: "apiMissingCompanyId",
  [normApiMessage("缺少 company_id 参数")]: "apiMissingCompanyId",
  [normApiMessage("Save failed")]: "saveFailed",
  [normApiMessage("保存失败")]: "saveFailed",
  [normApiMessage("Saved")]: "saved",
  [normApiMessage("保存成功")]: "saved",
};

function userListMessageLanguageHint(message) {
  const text = String(message || "");
  const hasCjk = /[\u4e00-\u9fff]/.test(text);
  const hasLatin = /[a-zA-Z]/.test(text);
  if (hasCjk && !hasLatin) return "zh";
  if (hasLatin && !hasCjk) return "en";
  return "mixed";
}

function translateUserListDynamicApiMessage(lang, message) {
  const raw = String(message || "").trim();
  if (!raw) return null;
  if (raw.includes("User updated successfully") && raw.includes("不再属于当前公司")) {
    return getUserListText(lang, "apiUserUpdatedCompanyNote");
  }
  if (raw.includes("User updated successfully") && raw.includes("no longer belongs to the current company")) {
    return getUserListText(lang, "apiUserUpdatedCompanyNote");
  }
  const fieldMatch = raw.match(/^Field '([^']+)' is required$/i);
  if (fieldMatch) return getUserListText(lang, "passwordRequired");
  return null;
}

/** Map backend API message to user-list i18n for toasts. */
export function translateUserListApiMessage(lang, apiMessage, fallbackKey = "", params = {}) {
  const message = String(apiMessage ?? "").trim();
  const locale = toLocale(lang);

  const dynamic = translateUserListDynamicApiMessage(locale, message);
  if (dynamic) return dynamic;

  const key = USER_LIST_API_MESSAGE_KEYS[normApiMessage(message)];
  if (key) return getUserListText(locale, key, params);

  const hint = userListMessageLanguageHint(message);
  if (message && hint !== "mixed" && hint !== locale && fallbackKey) {
    return getUserListText(locale, fallbackKey, params);
  }

  return message || (fallbackKey ? getUserListText(locale, fallbackKey, params) : "");
}

const USER_ROLE_I18N_KEYS = {
  partnership: "rolePartnership",
  admin: "roleAdmin",
  manager: "roleManager",
  supervisor: "roleSupervisor",
  accountant: "roleAccountant",
  audit: "roleAudit",
  "customer service": "roleCustomerService",
  company: "roleCompany",
  owner: "roleOwner",
};

/** User list table / modal: localized role badge */
export function formatUserRoleDisplay(t, role) {
  const key = USER_ROLE_I18N_KEYS[String(role || "").trim().toLowerCase()];
  if (key) return t(key);
  return String(role || "").toUpperCase();
}

/** User list table: localized status badge */
export function formatUserStatusDisplay(t, status) {
  const s = String(status || "").trim().toLowerCase();
  if (s === "active") return t("statusActive");
  if (s === "inactive") return t("statusInactive");
  return String(status || "").toUpperCase();
}

export const getUserListText = createGetText(USER_LIST_I18N);
