export const DASHBOARD_I18N = {
  en: {
    transactionDashboard: "Transaction Dashboard",
    filterSection: "Filters",
    captureDate: "Capture Date",
    dateRange: "Date Range:",
    thanLastMonth: "than last month",
    thanPreviousPeriod: "than previous period",
    selectDateRange: "Select date range",
    selectEndDate: "Select end date",
    periodShortcutsAria: "Period shortcuts",
    groupAndCompany: "Group / Company",
    selectGroup: "Select group",
    selectCompany: "Select company",
    settlementCurrency: "Settlement currency",
    confirm: "Confirm",
    selectedCompaniesCount: "{n} selected",
    companiesUnit: "companies",
    quickPeriod: "Quick period",
    period: "Period",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",
    groupId: "Group ID:",
    company: "Company:",
    all: "All",
    currency: "Currency:",
    currencyDragHint: "Drag to reorder · Click to filter",
    earnings: "Earnings",
    profit: "Profit",
    expenses: "Expenses",
    netProfit: "Net Profit",
    netProfitChart: "Net Profit",
    trendChart: "Trend Chart",
    statistics: "Statistics",
    periodSummary: "Period Summary",
    to: "to",
    couldNotSwitchCompany: "Could not switch company",
    dashboardApiError: "Dashboard API error",
    failedToLoadDashboard: "Failed to load dashboard",
    sidebarHome: "Home",
    sidebarDomain: "Domain",
    sidebarAnnouncement: "Announcement",
    sidebarAutoRenew: "Auto Renew",
    sidebarAdmin: "Admin",
    sidebarAccount: "Account",
    sidebarOwnership: "Ownership",
    sidebarProcess: "Process",
    sidebarDataCapture: "Data Capture",
    sidebarTransactionPayment: "Transaction Payment",
    sidebarReport: "Report",
    sidebarCustomerReport: "Customer Report",
    sidebarDomainReport: "Domain Report",
    sidebarMaintenance: "Maintenance",
    sidebarTransaction: "Transaction",
    sidebarPayment: "Payment",
    sidebarBankProcess: "Process",
    sidebarFormula: "Formula",
    exp: "Exp:",
    expNoDate: "No expiry",
    logout: "Logout",
    announcements: "Announcements",
    loadingAnnouncements: "Loading announcements...",
    noAnnouncements: "No announcements",
    notifications: "Notifications",
    close: "Close",
    chooseAvatar: "Choose Avatar",
    male: "Male",
    female: "Female",
    user: "User",
    switchLanguage: "Switch language",
    sidebarCollapse: "Collapse sidebar",
    sidebarExpand: "Expand sidebar",
    confirmLogoutTitle: "Confirm Logout",
    confirmLogoutMessage: "Are you sure you want to logout?",
    cancel: "Cancel",
    loggingOut: "Logging out...",
    weekdays: ["S", "M", "T", "W", "T", "F", "S"],
    weekdaysShort: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    monthLabels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    locale: "en-US",
    convertedApprox: "≈ {amount} {code}",
    rateFootnote: "{codes} converted via Frankfurter · {date}",
    earningsIncludesConversion: "Includes multi-currency conversion",
    rateUnavailable: "Some rates unavailable",
    rateLoading: "Loading rates…",
    rateSourceLabel: "Frankfurter",
    currencyBreakdown: "Breakdown",
    breakdownCurrency: "Currency",
    breakdownAmount: "Amount",
    breakdownOriginalAmount: "Original Amount",
    breakdownRate: "Rate",
    breakdownShare: "Share",
    shareOfTotal: "Share of total",
    nativeAmountIn: "{amount} {code}",
    rateOneUnit: "1 {from} = {rate} {base}",
    earningsChartTab: "Currency",
    netProfitChartTab: "Net Profit",
    earningChartTab: "Earning",
    earningsCompanyCaption: "Earnings",
    companyBreakdown: "Company breakdown",
    breakdownCompany: "Company",
    breakdownGroup: "Group",
    myShare: "My share",
    netProfitCompanyCaption: "Net Profit",
  },
  zh: {
    transactionDashboard: "交易仪表板",
    filterSection: "筛选",
    captureDate: "捕获日期",
    dateRange: "日期范围:",
    thanLastMonth: "较上月",
    thanPreviousPeriod: "较上一周期",
    selectDateRange: "选择日期范围",
    selectEndDate: "选择结束日期",
    periodShortcutsAria: "周期快捷",
    groupAndCompany: "集团 / 公司",
    selectGroup: "选择集团",
    selectCompany: "选择公司",
    settlementCurrency: "结算货币",
    confirm: "确认",
    selectedCompaniesCount: "已选 {n} 家",
    companiesUnit: "家",
    quickPeriod: "快捷周期",
    period: "周期",
    today: "今天",
    yesterday: "昨天",
    thisWeek: "本周",
    lastWeek: "上周",
    thisMonth: "本月",
    lastMonth: "上月",
    thisYear: "今年",
    lastYear: "去年",
    groupId: "集团:",
    company: "公司:",
    all: "全部",
    currency: "币种:",
    currencyDragHint: "拖动调整顺序 · 点击筛选",
    earnings: "收益",
    profit: "盈利",
    expenses: "支出",
    netProfit: "净盈利",
    netProfitChart: "净盈利",
    trendChart: "趋势图",
    statistics: "统计",
    periodSummary: "期间汇总",
    to: "至",
    couldNotSwitchCompany: "无法切换公司",
    dashboardApiError: "仪表板接口错误",
    failedToLoadDashboard: "加载仪表板失败",
    sidebarHome: "主页",
    sidebarDomain: "域名",
    sidebarAnnouncement: "公告",
    sidebarAutoRenew: "自动续费",
    sidebarAdmin: "管理",
    sidebarAccount: "账号",
    sidebarOwnership: "股权",
    sidebarProcess: "流程",
    sidebarDataCapture: "数据采集",
    sidebarTransactionPayment: "交易支付",
    sidebarReport: "报表",
    sidebarCustomerReport: "客户报表",
    sidebarDomainReport: "域名报表",
    sidebarMaintenance: "维护",
    sidebarTransaction: "交易",
    sidebarPayment: "支付",
    sidebarBankProcess: "流程",
    sidebarFormula: "公式",
    exp: "到期:",
    expNoDate: "无到期",
    logout: "登出",
    announcements: "公告",
    loadingAnnouncements: "正在加载公告...",
    noAnnouncements: "暂无公告",
    notifications: "通知",
    close: "关闭",
    chooseAvatar: "选择头像",
    male: "男",
    female: "女",
    user: "用户",
    switchLanguage: "切换语言",
    sidebarCollapse: "收起侧边栏",
    sidebarExpand: "展开侧边栏",
    confirmLogoutTitle: "确认登出",
    confirmLogoutMessage: "确定要登出吗？",
    cancel: "取消",
    loggingOut: "登出中...",
    weekdays: ["日", "一", "二", "三", "四", "五", "六"],
    weekdaysShort: ["日", "一", "二", "三", "四", "五", "六"],
    monthLabels: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    locale: "zh-CN",
    convertedApprox: "≈ {amount} {code}",
    rateFootnote: "{codes} 按 Frankfurter 汇率折算 · {date}",
    earningsIncludesConversion: "含多币种折算",
    rateUnavailable: "部分币种无在线汇率",
    rateLoading: "加载汇率中…",
    rateSourceLabel: "Frankfurter",
    currencyBreakdown: "构成",
    breakdownCurrency: "币种",
    breakdownAmount: "金额",
    breakdownOriginalAmount: "原始金额",
    breakdownRate: "汇率",
    breakdownShare: "占比",
    shareOfTotal: "占总比",
    nativeAmountIn: "{amount} {code}",
    rateOneUnit: "1 {from} = {rate} {base}",
    earningsChartTab: "币种",
    netProfitChartTab: "净盈利",
    earningChartTab: "收益",
    earningsCompanyCaption: "收益",
    companyBreakdown: "公司构成",
    breakdownCompany: "公司",
    breakdownGroup: "集团",
    myShare: "我的份额",
    netProfitCompanyCaption: "净盈利",
  },
};
